// doc-pages/component-floating-filter/examples/custom-filter-and-floating-filter/_gen/modules/react/numberFilterComponent.jsx
import React, { Component, createRef } from 'react';

export default class NumberFilterComponent extends Component {
  constructor(props) {
    super(props);

    this.state = {
      filterText: null,
    };

    this.inputRef = createRef();
  }

  doesFilterPass(params) {
    if (!this.isFilterActive()) {
      return;
    }

    const { api, colDef, column, columnApi, context, valueGetter } = this.props;
    const { node } = params;

    const value = valueGetter({
      api,
      colDef,
      column,
      columnApi,
      context,
      data: node.data,
      getValue: (field) => node.data[field],
      node,
    });

    if (!value) return false;
    return Number(value) > Number(this.state.filterText);
  }

  isFilterActive() {
    return (
      this.state.filterText !== null &&
      this.state.filterText !== undefined &&
      this.state.filterText !== '' &&
      this.isNumeric(this.state.filterText)
    );
  }

  isNumeric(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  }

  getModel() {
    return this.isFilterActive() ? Number(this.state.filterText) : null;
  }

  setModel(model) {
    this.setState({ filterText: model }, this.props.filterChangedCallback);
  }

  onInputBoxChanged = (event) => {
    this.setState(
      { filterText: event.target.value },
      this.props.filterChangedCallback
    );
  };

  myMethodForTakingValueFromFloatingFilter(value) {
    this.setState({ filterText: value }, () => {
      this.inputRef.current.value = this.state.filterText;
      this.props.filterChangedCallback();
    });
  }

  render() {
    return (
      <div style={{ padding: '4px' }}>
        <div style={{ fontWeight: 'bold' }}>Greater than:</div>
        <div>
          <input
            ref={this.inputRef}
            style={{ margin: '4px 0 4px 0' }}
            type="number"
            onInput={this.onInputBoxChanged}
            placeholder="Number of medals..."
          />
        </div>
      </div>
    );
  }
}

// doc-pages/component-floating-filter/examples/custom-filter-and-floating-filter/_gen/modules/angular/app/number-filter-component.component.ts
import { IFilterAngularComp } from '@ag-grid-community/angular';
import { IDoesFilterPassParams, IFilterParams } from '@ag-grid-community/core';
import { Component } from '@angular/core';

@Component({
  selector: 'number-component',
  template: `
    <div style="padding: 4px">
      <div style="font-weight: bold;">Greater than:</div>
      <div>
        <input
          style="margin: 4px 0 4px 0;"
          type="number"
          [(ngModel)]="filterText"
          (input)="onInputBoxChanged($event)"
          placeholder="Number of medals..."
        />
      </div>
    </div>
  `,
})
export class NumberFilterComponent implements IFilterAngularComp {
  params!: IFilterParams;
  filterText: number | null | string = null;

  agInit(params: IFilterParams): void {
    this.params = params;
  }

  doesFilterPass(params: IDoesFilterPassParams) {
    if (!this.isFilterActive()) {
      return true;
    }

    var { api, colDef, column, columnApi, context, valueGetter } = this.params;
    var { node } = params;

    var value = valueGetter({
      api,
      colDef,
      column,
      columnApi,
      context,
      data: node.data,
      getValue: (field) => node.data[field],
      node,
    });

    if (!value) return false;
    return Number(value) > Number(this.filterText);
  }

  isFilterActive() {
    return (
      this.filterText !== null &&
      this.filterText !== undefined &&
      this.filterText !== '' &&
      this.isNumeric(this.filterText)
    );
  }

  isNumeric(n: any) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  }

  getModel() {
    return this.isFilterActive() ? Number(this.filterText) : null;
  }

  setModel(model: any) {
    this.filterText = model;
    this.params.filterChangedCallback();
  }

  myMethodForTakingValueFromFloatingFilter(value: any) {
    this.filterText = value;
    this.params.filterChangedCallback();
  }

  onInputBoxChanged() {
    this.params.filterChangedCallback();
  }
}
