// doc-pages/component-floating-filter/examples/custom-filter-and-floating-filter/_gen/packages/reactFunctionalTs/numberFloatingFilterComponent.tsx
import React, {
  Fragment,
  forwardRef,
  useImperativeHandle,
  useRef,
  useState,
} from 'react';
import { IFloatingFilterParams } from 'ag-grid-community';

export default forwardRef((props: IFloatingFilterParams<any>, ref) => {
  const inputRef = useRef<HTMLInputElement>(null);

  // expose AG Grid Filter Lifecycle callbacks
  useImperativeHandle(ref, () => {
    return {
      onParentModelChanged(parentModel: number | null) {
        // When the filter is empty we will receive a null value here
        if (!parentModel) {
          inputRef.current!.value;
        } else {
          inputRef.current!.value = parentModel + '';
        }
      },
    };
  });

  const onInputBoxChanged = (input: any) => {
    const value = input.target.value;
    if (value === '') {
      // Remove the filter
      props.parentFilterInstance((instance) => {
        instance.myMethodForTakingValueFromFloatingFilter(null);
      });
      return;
    }

    props.parentFilterInstance((instance) => {
      instance.myMethodForTakingValueFromFloatingFilter(value);
    });
  };

  return (
    <Fragment>
      &gt;{' '}
      <input
        ref={inputRef}
        style={{ width: '30px' }}
        type="number"
        min="0"
        onInput={onInputBoxChanged}
      />
    </Fragment>
  );
});

// doc-pages/component-floating-filter/examples/custom-filter-and-floating-filter/_gen/modules/angular/app/number-floating-filter-component.component.ts
import { IFloatingFilterAngularComp } from "@ag-grid-community/angular";
import { IFloatingFilterParams } from "@ag-grid-community/core";
import { Component } from "@angular/core";

@Component({
  selector: "number-component",
  template: `&gt;
    <input
      style="width: 30px"
      type="number"
      min="0"
      [(ngModel)]="currentValue"
      (input)="onInputBoxChanged()"
    />`,
})
export class NumberFloatingFilterComponent
  implements IFloatingFilterAngularComp
{
  params!: IFloatingFilterParams;
  currentValue: number | null | string = null;

  agInit(params: IFloatingFilterParams): void {
    this.params = params;
  }

  onParentModelChanged(parentModel: any) {
    // When the filter is empty we will receive a null value here
    if (!parentModel) {
      this.currentValue = null;
    } else {
      this.currentValue = parentModel;
    }
  }

  onInputBoxChanged() {
    if (!this.currentValue) {
      // Remove the filter
      this.params.parentFilterInstance((instance: any) => {
        instance.myMethodForTakingValueFromFloatingFilter(null);
      });
      return;
    }

    this.params.parentFilterInstance((instance: any) => {
      instance.myMethodForTakingValueFromFloatingFilter(this.currentValue);
    });
  }
}
