// doc-pages/master-detail-custom-detail/examples/custom-detail-with-refresh/_gen/modules/angular/app/detail-cell-renderer.component.ts
import { ICellRendererAngularComp } from "@ag-grid-community/angular";
import { ICellRendererParams } from "@ag-grid-community/core";
import { Component } from "@angular/core";

@Component({
  selector: "app-detail-cell-renderer",
  template: `
    <div>
      <form>
        <div>
          <p>
            <label>
              Calls:<br />
              <input type="text" value="{{ callsCount }}" />
            </label>
          </p>
          <p>
            <label>
              Last Updated:
              {{ now }}
            </label>
          </p>
        </div>
      </form>
    </div>
  `,
})
export class DetailCellRenderer implements ICellRendererAngularComp {
  public callsCount!: number;
  public now!: string;

  // called on init
  agInit(params: ICellRendererParams): void {
    this.callsCount = params.data.calls;
    this.now = new Date().toLocaleTimeString();
  }

  // called when the cell is refreshed
  refresh(params: ICellRendererParams): boolean {
    // check and see if we need to get the grid to tear this
    // component down and update it again
    if (params.data.calls != this.callsCount) {
      return false;
    } else {
      return true;
    }
  }
}

// doc-pages/master-detail-custom-detail/examples/custom-detail-with-refresh/_gen/packages/reactFunctionalTs/detailCellRenderer.tsx
import React, { useState } from 'react';
import { ICellRendererParams } from 'ag-grid-community';

const DetailCellRenderer = (props: ICellRendererParams) => {
  const [callCount, setCallCount] = useState(props.data.calls);

  return (
    <div>
      <form>
        <div>
          <p>
            <label>
              Calls:
              <br />
              <input
                type="text"
                value={callCount}
                onChange={(e) => setCallCount(e.target.value)}
              />
            </label>
          </p>
          <p>
            <label>Last Updated: {new Date().toLocaleTimeString()}</label>
          </p>
        </div>
      </form>
    </div>
  );
};

export default DetailCellRenderer;
