// doc-pages/component-status-bar/examples/custom-component/_gen/modules/reactFunctional/clickableStatusBarComponent.jsx
import React from 'react';

export default (props) => {
  const onClick = () => {
    alert('Selected Row Count: ' + props.api.getSelectedRows().length);
  };

  return (
    <div className="ag-status-name-value">
      <span>
        Status Bar Component&nbsp;
        <input type="button" onClick={() => onClick()} value="Click Me" />
      </span>
    </div>
  );
};

// doc-pages/component-status-bar/examples/custom-component/_gen/modules/angular/app/clickable-status-bar-component.component.ts
import { Component } from '@angular/core';
import { IStatusPanelParams } from '@ag-grid-community/core';
import { IStatusPanelAngularComp } from '@ag-grid-community/angular';


@Component({
    selector: 'status-component',
    template: `
        <div class="ag-status-name-value">
            <span class="component">Status Bar Component <input type="button" (click)="onClick()"
                                                                value="Click Me"/></span>
        </div>
    `
})
export class ClickableStatusBarComponent implements IStatusPanelAngularComp {
    private params!: IStatusPanelParams;

    agInit(params: IStatusPanelParams): void {
        this.params = params;
    }

    onClick(): void {
        alert('Selected Row Count: ' + this.params.api.getSelectedRows().length)
    }
}
