// doc-pages/row-pinning/examples/row-pinning/_gen/packages/reactFunctionalTs/customPinnedRowRenderer.tsx
import React, { Component } from 'react';
import { ICellRendererParams } from 'ag-grid-community';

interface CellStyle {
  [cssProperty: string]: string | number;
}
export default class CustomPinnedRowRenderer extends Component<
  ICellRendererParams & { style: CellStyle }
> {
  render() {
    return <span style={this.props.style}>{this.props.value}</span>;
  }
}

// doc-pages/row-pinning/examples/row-pinning/_gen/modules/angular/app/custom-pinned-row-renderer.component.ts
import { Component } from '@angular/core';
import { ICellRendererAngularComp } from '@ag-grid-community/angular';
import { ICellRendererParams } from '@ag-grid-community/core';

@Component({
    selector: 'floating-cell',
    template: `<span [ngStyle]="style">{{params.value}}</span>`
})
export class CustomPinnedRowRenderer implements ICellRendererAngularComp {
    public params: any;
    public style!: string;

    agInit(params: any): void {
        this.params = params;
        this.style = this.params.style;
    }

    refresh(): boolean {
        return false;
    }
}
