// doc-pages/drag-and-drop/examples/custom-drag-comp/_gen/packages/angular/app/drag-source-renderer.component.ts
import { Component } from "@angular/core";
import { ICellRendererAngularComp } from "ag-grid-angular";
import { ICellRendererParams } from "ag-grid-community";

@Component({
  selector: "child-cell",
  template: ` <div draggable="true" (dragstart)="onDragStart($event)">
    Drag Me!
  </div>`,
})
export class DragSourceRenderer implements ICellRendererAngularComp {
  public params!: ICellRendererParams;

  agInit(params: ICellRendererParams): void {
    this.params = params;
  }

  onDragStart(dragEvent: DragEvent) {
    var userAgent = window.navigator.userAgent;
    dragEvent.dataTransfer!.setData(
      "text/plain",
      "Dragged item with ID: " + this.params.node.data.id
    );
  }

  refresh(params: ICellRendererParams): boolean {
    return false;
  }
}

// doc-pages/drag-and-drop/examples/custom-drag-comp/_gen/packages/reactFunctionalTs/dragSourceRenderer.tsx
import React, { Component } from 'react';
import { ICellRendererParams } from 'ag-grid-community';

export default class DragSourceRenderer extends Component<ICellRendererParams> {
  constructor(props: ICellRendererParams) {
    super(props);
  }

  onDragStart = (dragEvent: any) => {
    var userAgent = window.navigator.userAgent;
    dragEvent.dataTransfer.setData(
      'text/plain',
      'Dragged item with ID: ' + this.props.node.data.id
    );
  };

  render() {
    return (
      <div draggable="true" onDragStart={this.onDragStart}>
        Drag Me!
      </div>
    );
  }
}
