// doc-pages/group-cell-renderer/examples/group-renderer/_gen/packages/angular/app/simple-cell-renderer.component.ts
import { Component } from "@angular/core";
import { ICellRendererParams } from "ag-grid-community";
import { ICellRendererAngularComp } from "ag-grid-angular";
import React from "react";

@Component({
  selector: "simple-component",
  template: `
    <span [style.backgroundColor]="color" style="padding: 2px">{{
      params.value
    }}</span>
  `,
})
export class SimpleCellRenderer implements ICellRendererAngularComp {
  public params!: ICellRendererParams;
  public color!: string;
  agInit(params: ICellRendererParams): void {
    this.params = params;
    this.color = this.params.node.group ? "coral" : "lightgreen";
  }

  refresh(params: ICellRendererParams) {
    return false;
  }
}

// doc-pages/group-cell-renderer/examples/group-renderer/_gen/modules/react/simpleCellRenderer.jsx
import React, { Component } from "react";

export default class SimpleCellRenderer extends Component {
  render() {
    return (
      <span
        style={{
          backgroundColor: this.props.node.group ? "coral" : "lightgreen",
          padding: 2,
        }}
      >
        {this.props.value}
      </span>
    );
  }
}
