// doc-pages/component-date/examples/custom-date/_gen/modules/react/customDateComponent.jsx
import React, { Component } from 'react';

export default class CustomDateComponent extends Component {
  constructor(props) {
    super(props);

    this.state = {
      date: null,
    };
  }

  render() {
    //Inlining styles to make simpler the component
    return (
      <div
        className="ag-input-wrapper custom-date-filter"
        role="presentation"
        ref="flatpickr"
      >
        <input type="text" ref="eInput" data-input style={{ width: '100%' }} />
        <a class="input-button" title="clear" data-clear>
          <i class="fa fa-times"></i>
        </a>
      </div>
    );
  }

  componentDidMount() {
    this.picker = flatpickr(this.refs.flatpickr, {
      onChange: this.onDateChanged.bind(this),
      dateFormat: 'd/m/Y',
      wrap: true,
    });

    this.eInput = this.refs.eInput;

    this.picker.calendarContainer.classList.add('ag-custom-component-popup');
  }

  //*********************************************************************************
  //          METHODS REQUIRED BY AG-GRID
  //*********************************************************************************

  getDate() {
    //ag-grid will call us here when in need to check what the current date value is hold by this
    //component.
    return this.state.date;
  }

  setDate(date) {
    //ag-grid will call us here when it needs this component to update the date that it holds.
    this.setState({ date });
    this.picker.setDate(date);
  }

  //*********************************************************************************
  //          AG-GRID OPTIONAL METHODS
  //*********************************************************************************

  setInputPlaceholder(placeholder) {
    this.eInput.setAttribute('placeholder', placeholder);
  }

  setInputAriaLabel(label) {
    this.eInput.setAttribute('aria-label', label);
  }

  //*********************************************************************************
  //          LINKS THE INTERNAL STATE AND AG-GRID
  //*********************************************************************************

  updateAndNotifyAgGrid(date) {
    //Callback after the state is set. This is where we tell ag-grid that the date has changed so
    //it will proceed with the filtering and we can then expect AG Grid to call us back to getDate
    this.setState({ date }, this.props.onDateChanged);
  }

  //*********************************************************************************
  //          LINKING THE UI, THE STATE AND AG-GRID
  //*********************************************************************************

  onDateChanged = (selectedDates) => {
    this.setState({ date: selectedDates[0] });
    this.updateAndNotifyAgGrid(selectedDates[0]);
  };
}

// doc-pages/component-date/examples/custom-date/_gen/modules/angular/app/custom-date-component.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { IDateParams } from '@ag-grid-community/core';
import { IDateAngularComp } from '@ag-grid-community/angular';


// we'll be using the globally provided flatpickr for our example
declare var flatpickr: any;

@Component({
    selector: 'app-loading-overlay',
    template: `
      <div #flatpickrEl class="ag-input-wrapper custom-date-filter" role="presentation">
      <input type="text" #eInput data-input style="width: 100%;"/>
      <a class='input-button' title='clear' data-clear>
        <i class='fa fa-times'></i>
      </a>
      </div>
    `,
    styles: [`
            .custom-date-filter a {
                position: absolute;
                right: 20px;
                color: rgba(0, 0, 0, 0.54);
                cursor: pointer;
            }

            .custom-date-filter:after {
                position: absolute;
                content: '\f073';
                display: block;
                font-weight: 400;
                font-family: 'Font Awesome 5 Free';
                right: 5px;
                pointer-events: none;
                color: rgba(0, 0, 0, 0.54);
            }
        `
    ]
})
export class CustomDateComponent implements IDateAngularComp {
    @ViewChild("flatpickrEl", { read: ElementRef }) flatpickrEl!: ElementRef;
    @ViewChild("eInput", { read: ElementRef }) eInput!: ElementRef;
    private date!: Date;
    private params!: IDateParams;
    private picker: any;

    agInit(params: IDateParams): void {
        this.params = params;
    }

    ngAfterViewInit(): void {
        this.picker = flatpickr(this.flatpickrEl.nativeElement, {
            onChange: this.onDateChanged.bind(this),
            wrap: true
        });

        this.picker.calendarContainer.classList.add('ag-custom-component-popup');
    }

    ngOnDestroy() {
        console.log(`Destroying DateComponent`);
    }

    onDateChanged(selectedDates: any) {
        this.date = selectedDates[0] || null;
        this.params.onDateChanged();
    }

    getDate(): Date {
        return this.date;
    }

    setDate(date: Date): void {
        this.date = date || null;
        this.picker.setDate(date);
    }

    setInputPlaceholder(placeholder: string): void {
        this.eInput.nativeElement.setAttribute('placeholder', placeholder);
    }

    setInputAriaLabel(label: string): void {
        this.eInput.nativeElement.setAttribute('aria-label', label);
    }
}
