// doc-pages/component-floating-filter/examples/floating-filter-component/_gen/modules/angular/app/slider-floating-filter.component.ts
import { AgFrameworkComponent } from "@ag-grid-community/angular";
import {
  IFloatingFilter,
  IFloatingFilterParams,
  NumberFilterModel,
} from "@ag-grid-community/core";
import { Component } from "@angular/core";

export interface SliderFloatingFilterParams extends IFloatingFilterParams {
  value: number;
  maxValue: number;
}

@Component({
  template: ` <input
    type="range"
    min="0"
    [max]="maxValue"
    data-show-value="true"
    data-popup-enabled="true"
    [(ngModel)]="currentValue"
    (ngModelChange)="valueChanged()"
  />`,
})
export class SliderFloatingFilter
  implements IFloatingFilter, AgFrameworkComponent<SliderFloatingFilterParams>
{
  private params!: SliderFloatingFilterParams;

  public maxValue!: number;
  public currentValue!: number;

  agInit(params: SliderFloatingFilterParams): void {
    this.params = params;
    this.maxValue = this.params.maxValue;
    this.currentValue = 0;
  }

  valueChanged() {
    const valueToUse = this.currentValue === 0 ? null : this.currentValue;
    this.params.parentFilterInstance(function (instance) {
      instance.onFloatingFilterChanged("greaterThan", valueToUse);
    });
  }

  onParentModelChanged(parentModel: NumberFilterModel): void {
    if (!parentModel) {
      this.currentValue = 0;
    } else {
      // note that the filter could be anything here, but our purposes we're assuming a greater than filter only,
      // so just read off the value and use that
      this.currentValue = parentModel.filter!;
    }
  }
}

// doc-pages/component-floating-filter/examples/floating-filter-component/_gen/modules/react/sliderFloatingFilter.jsx
import React, { Component } from "react";

export default class SliderFloatingFilter extends Component {
  constructor(props) {
    super(props);

    this.state = {
      maxValue: props.maxValue,
      currentValue: 0,
    };
  }

  valueChanged = (event) => {
    this.setState(
      {
        currentValue: event.target.value,
      },
      () => {
        let valueToUse =
          this.state.currentValue === "0" ? null : this.state.currentValue;
        this.props.parentFilterInstance(function (instance) {
          instance.onFloatingFilterChanged("greaterThan", valueToUse);
        });
      }
    );
  };

  onParentModelChanged(parentModel) {
    // note that the filter could be anything here, but our purposes we're assuming a greater than filter only,
    // so just read off the value and use that
    this.setState({
      currentValue: !parentModel ? 0 : parentModel.filter,
    });
  }

  render() {
    return (
      <input
        type="range"
        value={this.state.currentValue}
        min={0}
        max={this.state.maxValue}
        step={1}
        onChange={this.valueChanged}
      />
    );
  }
}
