// doc-pages/component-status-bar/examples/component-instance/_gen/modules/reactFunctionalTs/clickableStatusBarComponent.tsx
import React, { forwardRef, useImperativeHandle, useState } from 'react';
import { IStatusPanelParams } from '@ag-grid-community/core';

export default forwardRef((props: IStatusPanelParams, ref) => {
  const [visible, setVisible] = useState(true);

  const onClick = () => {
    alert('Selected Row Count: ' + props.api.getSelectedRows().length);
  };

  useImperativeHandle(ref, () => {
    return {
      setVisible: (visible: boolean) => {
        setVisible(visible);
      },
      isVisible: () => {
        return visible;
      },
    };
  });

  if (visible) {
    return (
      <div className="container">
        <div>
          <span className="component">
            Status Bar Component&nbsp;
            <input type="button" onClick={() => onClick()} value="Click Me" />
          </span>
        </div>
      </div>
    );
  }

  return null;
});

// doc-pages/component-status-bar/examples/component-instance/_gen/packages/angular/app/clickable-status-bar-component.component.ts
import { IStatusPanelParams } from "ag-grid-community";
import { Component } from "@angular/core";
import { IStatusPanelAngularComp } from "ag-grid-angular";

@Component({
  selector: "status-component",
  template: `
    <div class="container" *ngIf="visible">
      <div>
        <span class="component"
          >Status Bar Component
          <input type="button" (click)="onClick()" value="Click Me"
        /></span>
      </div>
    </div>
  `,
})
export class ClickableStatusBarComponent implements IStatusPanelAngularComp {
  private params!: IStatusPanelParams;
  private visible = true;

  agInit(params: IStatusPanelParams): void {
    this.params = params;
  }

  onClick(): void {
    alert("Selected Row Count: " + this.params.api.getSelectedRows().length);
  }

  setVisible(visible: boolean) {
    this.visible = visible;
  }

  isVisible(): boolean {
    return this.visible;
  }
}
