// doc-pages/component-tool-panel/examples/custom-stats/_gen/modules/angular/app/custom-stats-tool-panel.component.ts
import { IToolPanelAngularComp } from '@ag-grid-community/angular';
import { IToolPanelParams, RowNode } from '@ag-grid-community/core';
import { Component } from '@angular/core';

@Component({
  selector: 'custom-stats',
  template: ` <div style="text-align: center">
    <span>
      <h2><i class="fa fa-calculator"></i> Custom Stats</h2>
      <dl style="font-size: large; padding: 30px 40px 10px 30px">
        <dt class="totalStyle">
          Total Medals: <b>{{ numMedals }}</b>
        </dt>
        <dt class="totalStyle">
          Total Gold: <b>{{ numGold }}</b>
        </dt>
        <dt class="totalStyle">
          Total Silver: <b>{{ numSilver }}</b>
        </dt>
        <dt class="totalStyle">
          Total Bronze: <b>{{ numBronze }}</b>
        </dt>
      </dl>
    </span>
  </div>`,
  styles: [
    `
      .totalStyle {
        padding-bottom: 15px;
      }
    `,
  ],
})
export class CustomStatsToolPanel implements IToolPanelAngularComp {
  private params!: IToolPanelParams;

  public numMedals!: number;
  public numGold!: number;
  public numSilver!: number;
  public numBronze!: number;

  agInit(params: IToolPanelParams): void {
    this.params = params;

    this.numMedals = 0;
    this.numGold = 0;
    this.numSilver = 0;
    this.numBronze = 0;

    // calculate stats when new rows loaded, i.e. onModelUpdated
    this.params.api.addEventListener(
      'modelUpdated',
      this.updateTotals.bind(this)
    );
  }

  updateTotals(): void {
    let numGold = 0,
      numSilver = 0,
      numBronze = 0;

    this.params.api.forEachNode((rowNode: RowNode) => {
      const data = rowNode.data;
      if (data.gold) numGold += data.gold;
      if (data.silver) numSilver += data.silver;
      if (data.bronze) numBronze += data.bronze;
    });

    this.numMedals = numGold + numSilver + numBronze;
    this.numGold = numGold;
    this.numSilver = numSilver;
    this.numBronze = numBronze;
  }

  refresh(): void {}
}

// doc-pages/component-tool-panel/examples/custom-stats/_gen/modules/reactFunctionalTs/customStatsToolPanel.tsx
import React, { useEffect, useState } from 'react';
import { IToolPanelParams } from '@ag-grid-community/core';

const totalStyle = { paddingBottom: '15px' };

export default (props: IToolPanelParams) => {
  const [numMedals, setNumMedals] = useState(0);
  const [numGold, setNumGold] = useState(0);
  const [numSilver, setNumSilver] = useState(0);
  const [numBronze, setNumBronze] = useState(0);

  const updateTotals = () => {
    let numGold = 0,
      numSilver = 0,
      numBronze = 0;

    props.api.forEachNode(function (rowNode) {
      const data = rowNode.data;

      if (data.gold) numGold += data.gold;
      if (data.silver) numSilver += data.silver;
      if (data.bronze) numBronze += data.bronze;
    });

    const numMedals = numGold + numSilver + numBronze;

    setNumMedals(numMedals);
    setNumGold(numGold);
    setNumSilver(numSilver);
    setNumBronze(numBronze);
  };

  useEffect(() => {
    props.api.addEventListener('modelUpdated', updateTotals);

    return () => props.api.removeEventListener('modelUpdated', updateTotals);
  }, []);

  return (
    <div style={{ textAlign: 'center' }}>
      <span>
        <h2>
          <i className="fa fa-calculator"></i> Custom Stats
        </h2>
        <dl style={{ fontSize: 'large', padding: '30px 40px 10px 30px' }}>
          <dt style={totalStyle}>
            Total Medals: <b>{numMedals}</b>
          </dt>
          <dt style={totalStyle}>
            Total Gold: <b>{numGold}</b>
          </dt>
          <dt style={totalStyle}>
            Total Silver: <b>{numSilver}</b>
          </dt>
          <dt style={totalStyle}>
            Total Bronze: <b>{numBronze}</b>
          </dt>
        </dl>
      </span>
    </div>
  );
};
