// doc-pages/full-width-rows/examples/basic-full-width/_gen/packages/reactFunctional/fullWidthCellRenderer.jsx
import React, { useState } from 'react';

export default (props) => {
  const [cssClass] = useState(
    props.node.rowPinned
      ? 'example-full-width-pinned-row'
      : 'example-full-width-row'
  );
  const [message] = useState(
    props.node.rowPinned
      ? `Pinned full width row at index ${props.rowIndex}`
      : `Normal full width row at index${props.rowIndex}`
  );

  return (
    <div className={cssClass}>
      <button onClick={() => alert('button clicked')}>Click</button>
      {message}
    </div>
  );
};

// doc-pages/full-width-rows/examples/basic-full-width/_gen/modules/angular/app/full-width-cell-renderer.component.ts
import { ICellRendererAngularComp } from "@ag-grid-community/angular";
import { ICellRendererParams } from "@ag-grid-community/core";
import { Component } from "@angular/core";

@Component({
  selector: "simple-component",
  template: ` <div [class]="cssClass">
    <button (click)="clicked()">Click</button>
    {{ message }}
  </div>`,
})
export class FullWidthCellRenderer implements ICellRendererAngularComp {
  private cssClass!: string;
  private message!: string;

  agInit(params: ICellRendererParams): void {
    this.cssClass = params.node.rowPinned
      ? "example-full-width-pinned-row"
      : "example-full-width-row";
    this.message = params.node.rowPinned
      ? `Pinned full width row at index ${params.rowIndex}`
      : `Normal full width row at index${params.rowIndex}`;
  }

  clicked() {
    alert("button clicked");
  }

  refresh() {
    return false;
  }
}
