// doc-pages/row-dragging/examples/dragger-inside-custom-start-drag-pixels/_gen/modules/reactFunctionalTs/customCellRenderer.tsx
import React, { useEffect, useRef } from 'react';
import { ICellRendererParams } from '@ag-grid-community/core';

const CustomCellRenderer = (props: ICellRendererParams) => {
  const myRef = useRef(null);

  useEffect(() => {
    props.registerRowDragger(myRef.current!, 0);
  });

  return (
    <div className="my-custom-cell-renderer">
      <div className="athlete-info">
        <span>{props.data.athlete}</span>
        <span>{props.data.country}</span>
      </div>
      <span>{props.data.year}</span>
      <i className="fas fa-arrows-alt-v" ref={myRef}></i>
    </div>
  );
};
export default CustomCellRenderer;

// doc-pages/row-dragging/examples/dragger-inside-custom-cell-renderer/_gen/modules/angular/app/custom-cell-renderer.component.ts
import { ICellRendererAngularComp } from '@ag-grid-community/angular';
import { ICellRendererParams } from '@ag-grid-community/core';
import { Component, ElementRef, HostBinding, ViewChild } from '@angular/core';

@Component({
  selector: 'custom-cell',
  /* html */
  template: `<div class="athlete-info">
      <span>{{ athlete }}</span>
      <span>{{ country }}</span>
    </div>
    <span>{{ year }}</span>
    <i class="fas fa-arrows-alt-v" #myref></i>`,
})
export class CustomCellRenderer implements ICellRendererAngularComp {
  public athlete!: string;
  public country!: string;
  public year!: string;
  private cellRendererParams!: ICellRendererParams;

  @ViewChild('myref') myRef!: ElementRef;
  @HostBinding('class') class = 'my-custom-cell-renderer';

  agInit(params: ICellRendererParams): void {
    this.cellRendererParams = params;
    this.athlete = params.data.athlete;
    this.country = params.data.country;
    this.year = params.data.year;
  }

  ngAfterViewInit() {
    this.cellRendererParams.registerRowDragger(this.myRef.nativeElement);
  }

  refresh(params: ICellRendererParams): boolean {
    return false;
  }
}
