// doc-pages/cell-rendering/examples/dynamic-rendering-component/_gen/packages/reactFunctionalTs/genderRenderer.tsx
import React from 'react';
import { ICellRendererParams } from 'ag-grid-community';
export default (props: ICellRendererParams) => {
  const image = props.value === 'Male' ? 'male.png' : 'female.png';
  const imageSource = `https://www.ag-grid.com/example-assets/genders/${image}`;
  return (
    <span>
      <img src={imageSource} />
      {props.value}
    </span>
  );
};

// doc-pages/cell-rendering/examples/dynamic-rendering-component/_gen/modules/angular/app/gender-renderer.component.ts
import { ICellRendererAngularComp } from "@ag-grid-community/angular";
import { ICellRendererParams } from "@ag-grid-community/core";
import { Component } from "@angular/core";

@Component({
  selector: "app-gender-renderer",
  template: ` <span> <img [src]="imageSource" />{{ value }} </span> `,
})
export class GenderRenderer implements ICellRendererAngularComp {
  public imageSource!: string;
  public value: any;

  agInit(params: ICellRendererParams): void {
    const image = params.value === "Male" ? "male.png" : "female.png";
    this.imageSource = `https://www.ag-grid.com/example-assets/genders/${image}`;
    this.value = params.value;
  }

  refresh(params: ICellRendererParams) {
    return false;
  }
}
