// doc-pages/component-header/examples/header-group-component/_gen/modules/angular/app/custom-header-group.component.ts
import { IHeaderGroupAngularComp } from '@ag-grid-community/angular';
import { IHeaderGroupParams } from '@ag-grid-community/core';
import { Component } from '@angular/core';
@Component({
  selector: 'app-custom-header-group',
  template: `
    <div class="ag-header-group-cell-label">
      <div class="customHeaderLabel">{{ params.displayName }}</div>
      <div
        class="customExpandButton"
        [ngClass]="expandState"
        (click)="expandOrCollapse()"
      >
        <i class="fa fa-arrow-right"></i>
      </div>
    </div>
  `,
  styles: [
    `
      .customExpandButton {
        float: right;
        margin-top: 2px;
        margin-left: 3px;
      }

      .expanded {
        animation-name: toExpanded;
        animation-duration: 1s;
        -webkit-transform: rotate(180deg); /* Chrome, Safari, Opera */
        transform: rotate(180deg);
      }

      .collapsed {
        color: cornflowerblue;
        animation-name: toCollapsed;
        animation-duration: 1s;
        -webkit-transform: rotate(0deg); /* Chrome, Safari, Opera */
        transform: rotate(0deg);
      }

      .customHeaderMenuButton,
      .customHeaderLabel,
      .customHeaderLabel,
      .customSortDownLabel,
      .customSortUpLabel,
      .customSortRemoveLabel {
        margin-top: 2px;
        margin-left: 4px;
        float: left;
      }

      .customSortDownLabel {
        margin-left: 10px;
      }

      .customSortUpLabel {
        margin-left: 1px;
      }

      .customSortRemoveLabel {
        float: left;
        font-size: 11px;
      }

      .active {
        color: cornflowerblue;
      }

      @keyframes toExpanded {
        from {
          color: cornflowerblue;
          -webkit-transform: rotate(0deg); /* Chrome, Safari, Opera */
          transform: rotate(0deg);
        }
        to {
          color: black;
          -webkit-transform: rotate(180deg); /* Chrome, Safari, Opera */
          transform: rotate(180deg);
        }
      }

      @keyframes toCollapsed {
        from {
          color: black;
          -webkit-transform: rotate(180deg); /* Chrome, Safari, Opera */
          transform: rotate(180deg);
        }
        to {
          color: cornflowerblue;
          -webkit-transform: rotate(0deg); /* Chrome, Safari, Opera */
          transform: rotate(0deg);
        }
      }
    `,
  ],
})
export class CustomHeaderGroup implements IHeaderGroupAngularComp {
  public params!: IHeaderGroupParams;
  public expandState!: string;

  agInit(params: IHeaderGroupParams): void {
    this.params = params;

    this.params.columnGroup
      .getProvidedColumnGroup()
      .addEventListener('expandedChanged', this.syncExpandButtons.bind(this));

    this.syncExpandButtons();
  }

  expandOrCollapse() {
    const currentState = this.params.columnGroup
      .getProvidedColumnGroup()
      .isExpanded();
    this.params.setExpanded(!currentState);
  }

  syncExpandButtons() {
    if (this.params.columnGroup.getProvidedColumnGroup().isExpanded()) {
      this.expandState = 'expanded';
    } else {
      this.expandState = 'collapsed';
    }
  }
}

// doc-pages/component-header/examples/header-group-component/_gen/modules/reactFunctionalTs/customHeaderGroup.tsx
import React, { useEffect, useState } from 'react';
import { IHeaderGroupParams } from '@ag-grid-community/core';

export default (props: IHeaderGroupParams) => {
  const [expandState, setExpandState] = useState('collapsed');

  const expandOrCollapse = () => {
    let currentState = props.columnGroup.getProvidedColumnGroup().isExpanded();
    props.setExpanded(!currentState);
  };

  const syncExpandButtons = () => {
    setExpandState(
      props.columnGroup.getProvidedColumnGroup().isExpanded()
        ? 'expanded'
        : 'collapsed'
    );
  };

  useEffect(() => {
    props.columnGroup
      .getProvidedColumnGroup()
      .addEventListener('expandedChanged', syncExpandButtons);
    syncExpandButtons();

    return () => {
      props.columnGroup
        .getProvidedColumnGroup()
        .removeEventListener('expandedChanged', syncExpandButtons);
    };
  }, []);

  return (
    <div className="ag-header-group-cell-label">
      <div className="customHeaderLabel">{props.displayName}</div>
      <div
        className={`customExpandButton ${expandState}`}
        onClick={() => expandOrCollapse()}
      >
        <i className="fa fa-arrow-right"></i>
      </div>
    </div>
  );
};
