// doc-pages/component-cell-renderer/examples/cell-renderer/provided/modules/angular/app/days-frost-renderer.component.ts
import { ICellRendererAngularComp } from "@ag-grid-community/angular";
import { ICellRendererParams } from "@ag-grid-community/core";
import { Component } from "@angular/core";

@Component({
  selector: "day-component",
  template: `<span
    ><img *ngFor="let number of value" [src]="rendererImage"
  /></span>`,
})
export class DaysFrostRenderer implements ICellRendererAngularComp {
  params!: ICellRendererParams & { rendererImage: string };
  rendererImage!: string;
  value!: any[];

  agInit(params: ICellRendererParams & { rendererImage: string }): void {
    this.params = params;
    this.updateImage();
  }

  updateImage() {
    this.rendererImage = `https://www.ag-grid.com/example-assets/weather/${this.params.rendererImage}`;
    this.value = new Array(this.params.value).fill(0);
  }

  refresh(params: ICellRendererParams & { rendererImage: string }) {
    this.params = params;
    this.updateImage();
    return true;
  }
}

// doc-pages/component-cell-renderer/examples/cell-renderer/_gen/packages/reactFunctionalTs/daysFrostRenderer.tsx
import { ICellRendererParams } from 'ag-grid-community';
import React from 'react';

export interface ImageCellRendererParams extends ICellRendererParams {
  rendererImage: string;
}

export default (props: ImageCellRendererParams) => (
  <span>
    {new Array(props.value).fill('').map((ignore) => (
      <img
        src={`https://www.ag-grid.com/example-assets/weather/${props.rendererImage}`}
      />
    ))}
  </span>
);
