// doc-pages/master-detail-custom-detail/examples/custom-detail-with-form/_gen/packages/angular/app/detail-cell-renderer.component.ts
import { Component } from '@angular/core';
import { ICellRendererAngularComp } from 'ag-grid-angular';

@Component({
    selector: 'app-detail-cell-renderer',
    template: `
        <div>
            <form>
                <div>
                    <p>
                        <label>
                            Call Id:<br>
                            <input type="text" value={{firstRecord.callId}}>
                        </label>
                    </p>
                    <p>
                        <label>
                            Number:<br>
                            <input type="text" value={{firstRecord.number}}>
                        </label>
                    </p>
                    <p>
                        <label>
                            Direction:<br>
                            <input type="text" value={{firstRecord.direction}}>
                        </label>
                    </p>
                </div>
            </form>
        </div>
    `
})
export class DetailCellRenderer implements ICellRendererAngularComp {
    firstRecord!: any;
    // called on init
    agInit(params: any): void {
        this.firstRecord = params.data.callRecords[0];
    }

    // called when the cell is refreshed
    refresh(params: any): boolean {
        return false;
    }
}

// doc-pages/master-detail-custom-detail/examples/custom-detail-with-form/_gen/modules/reactFunctionalTs/detailCellRenderer.tsx
import React, { useState } from 'react';
import { ICellRendererParams } from '@ag-grid-community/core';

const DetailCellRenderer = ({ data }: ICellRendererParams) => {
  const firstRecord = data.callRecords[0];
  const [callId, setCallId] = useState(firstRecord.callId);
  const [number, setNumber] = useState(firstRecord.number);
  const [direction, setDirection] = useState(firstRecord.direction);

  return (
    <div>
      <form>
        <div>
          <p>
            <label>
              Call Id:
              <br />
              <input
                type="text"
                value={callId}
                onChange={(e) => setCallId(e.target.value)}
              />
            </label>
          </p>
          <p>
            <label>
              Number:
              <br />
              <input
                type="text"
                value={number}
                onChange={(e) => setNumber(e.target.value)}
              />
            </label>
          </p>
          <p>
            <label>
              Direction:
              <br />
              <input
                type="text"
                value={direction}
                onChange={(e) => setDirection(e.target.value)}
              />
            </label>
          </p>
        </div>
      </form>
    </div>
  );
};

export default DetailCellRenderer;
