// doc-pages/component-cell-renderer/examples/get-cell-renderer/_gen/packages/react/medalCellRenderer.jsx
import React, { Component } from 'react';

export default class MedalCellRenderer extends Component {
  medalUserFunction() {
    console.log(
      `user function called for medal column: row = ${
        this.props.rowIndex
      }, column = ${this.props.column.getId()}`
    );
  }

  render() {
    return <span>{new Array(this.props.value).fill('#').join('')}</span>;
  }
}

// doc-pages/component-cell-renderer/examples/get-cell-renderer/_gen/modules/angular/app/medal-cell-renderer.component.ts
import { Component } from "@angular/core";
import { ICellRendererAngularComp } from "@ag-grid-community/angular";
import { ICellRendererParams } from "@ag-grid-community/core";

@Component({
  selector: "medal-component",
  template: `<span>{{ this.displayValue }}</span>`,
})
export class MedalCellRenderer implements ICellRendererAngularComp {
  private params!: ICellRendererParams;
  public displayValue!: string;

  agInit(params: ICellRendererParams): void {
    this.params = params;
    this.displayValue = new Array(params.value).fill("#").join("");
  }

  medalUserFunction() {
    console.log(
      `user function called for medal column: row = ${
        this.params.rowIndex
      }, column = ${this.params.column!.getId()}`
    );
  }
  refresh(params: ICellRendererParams) {
    return false;
  }
}
