// doc-pages/component-status-bar/examples/simple-component/_gen/modules/angular/app/clickable-status-bar-component.component.ts
import { IStatusPanelAngularComp } from '@ag-grid-community/angular';
import { IStatusPanelParams } from '@ag-grid-community/core';
import { Component } from '@angular/core';

@Component({
  selector: 'status-component',
  template: `<input
    type="button"
    (click)="onClick()"
    value="Click Me For Selected Row Count"
  />`,
  styles: ['input { padding: 5px; margin: 5px }'],
})
export class ClickableStatusBarComponent implements IStatusPanelAngularComp {
  private params!: IStatusPanelParams;

  agInit(params: IStatusPanelParams): void {
    this.params = params;
  }

  onClick(): void {
    alert('Selected Row Count: ' + this.params.api.getSelectedRows().length);
  }
}

// doc-pages/component-status-bar/examples/simple-component/_gen/packages/reactFunctionalTs/clickableStatusBarComponent.tsx
import React from 'react';
import { IStatusPanelParams } from 'ag-grid-community';

export default (props: IStatusPanelParams) => {
  const onClick = () => {
    alert('Selected Row Count: ' + props.api.getSelectedRows().length);
  };

  const style = {
    padding: 5,
    margin: 5,
  };

  return (
    <input
      style={style}
      type="button"
      onClick={onClick}
      value="Click Me For Selected Row Count"
    />
  );
};
