// doc-pages/component-filter/examples/filter-component/_gen/modules/react/partialMatchFilter.jsx
import React, { Component } from "react";
import ReactDOM from "react-dom";

export default class PartialMatchFilter extends Component {
  constructor(props) {
    super(props);

    this.state = {
      text: "",
    };

    this.onChange = this.onChange.bind(this);
  }

  isFilterActive() {
    return this.state.text != null && this.state.text !== "";
  }

  doesFilterPass(params) {
    const { api, colDef, column, columnApi, context, valueGetter } = this.props;
    const { node } = params;
    const value = valueGetter({
      api,
      colDef,
      column,
      columnApi,
      context,
      data: node.data,
      getValue: (field) => node.data[field],
      node,
    })
      .toString()
      .toLowerCase();

    return this.state.text
      .toLowerCase()
      .split(" ")
      .every((filterWord) => value.indexOf(filterWord) >= 0);
  }

  getModel() {
    if (!this.isFilterActive()) {
      return null;
    }

    return { value: this.state.text };
  }

  setModel(model) {
    this.state.text = model ? model.value : "";
  }

  afterGuiAttached(params) {
    this.focus();
  }

  focus() {
    window.setTimeout(() => {
      const container = ReactDOM.findDOMNode(this.refs.input);

      if (container) {
        container.focus();
      }
    });
  }

  componentMethod(message) {
    alert(`Alert from PartialMatchFilterComponent: ${message}`);
  }

  onChange(event) {
    const newValue = event.target.value;

    if (this.state.text !== newValue) {
      this.setState(
        {
          text: newValue,
        },
        () => {
          this.props.filterChangedCallback();
        }
      );
    }
  }

  render() {
    const style = {
      border: "2px solid #22ff22",
      borderRadius: "5px",
      backgroundColor: "#bbffbb",
      width: "200px",
      height: "50px",
    };

    return (
      <div style={style}>
        Filter:{" "}
        <input
          style={{ height: "20px" }}
          ref="input"
          value={this.state.text}
          onChange={this.onChange}
          className="form-control"
        />
      </div>
    );
  }
}

// doc-pages/component-filter/examples/filter-component/_gen/modules/angular/app/partial-match-filter.component.ts
import { Component, ViewChild, ViewContainerRef } from "@angular/core";
import {
  IAfterGuiAttachedParams,
  IDoesFilterPassParams,
  IFilterParams,
} from "@ag-grid-community/core";
import { IFilterAngularComp } from "@ag-grid-community/angular";

@Component({
  selector: "filter-cell",
  template: `
    <div class="container">
      Partial Match Filter:
      <input
        #input
        (ngModelChange)="onChange($event)"
        [ngModel]="text"
        class="form-control"
      />
    </div>
  `,
  styles: [
    `
      .container {
        border: 2px solid #22ff22;
        border-radius: 5px;
        background-color: #bbffbb;
        width: 200px;
        height: 50px;
      }

      input {
        height: 20px;
      }
    `,
  ],
})
export class PartialMatchFilter implements IFilterAngularComp {
  private params!: IFilterParams;
  public text = "";

  @ViewChild("input", { read: ViewContainerRef })
  public input!: ViewContainerRef;

  agInit(params: IFilterParams): void {
    this.params = params;
  }

  isFilterActive(): boolean {
    return this.text != null && this.text !== "";
  }

  doesFilterPass(params: IDoesFilterPassParams): boolean {
    const { api, colDef, column, columnApi, context, valueGetter } =
      this.params;
    const { node } = params;
    const value = valueGetter({
      api,
      colDef,
      column,
      columnApi,
      context,
      data: node.data,
      getValue: (field) => node.data[field],
      node,
    })
      .toString()
      .toLowerCase();

    return this.text
      .toLowerCase()
      .split(" ")
      .every((filterWord) => value.indexOf(filterWord) >= 0);
  }

  getModel(): any {
    if (!this.isFilterActive()) {
      return null;
    }

    return { value: this.text };
  }

  setModel(model: any): void {
    this.text = model ? model.value : "";
  }

  afterGuiAttached(params: IAfterGuiAttachedParams): void {
    window.setTimeout(() => this.input.element.nativeElement.focus());
  }

  componentMethod(message: string): void {
    alert(`Alert from PartialMatchFilterComponent: ${message}`);
  }

  onChange(newValue: any): void {
    if (this.text !== newValue) {
      this.text = newValue;
      this.params.filterChangedCallback();
    }
  }
}
