// doc-pages/component-status-bar/examples/custom-component/_gen/modules/angular/app/count-status-bar-component.component.ts
import { Component } from '@angular/core';
import { IStatusPanelParams } from '@ag-grid-community/core';
import { IStatusPanelAngularComp } from '@ag-grid-community/angular';


@Component({
    selector: 'status-component',
    template: `
        <div class="ag-status-name-value">
            <span>Row Count Component&nbsp;:</span>
            <span class="ag-status-name-value-value">{{count}}</span>
        </div>
    `
})
export class CountStatusBarComponent implements IStatusPanelAngularComp {
    private params!: IStatusPanelParams;
    public count: number | null = null;

    agInit(params: IStatusPanelParams): void {
        this.params = params;

        this.params.api.addEventListener('gridReady', this.onGridReady.bind(this));
    }

    onGridReady() {
        this.count = this.params.api.getModel().getRowCount();
    }
}

// doc-pages/component-status-bar/examples/custom-component/_gen/packages/react/countStatusBarComponent.jsx
import React, { Component } from 'react';

export default class CountStatusBarComponent extends Component {
  constructor(props) {
    super(props);

    this.state = {
      count: 10,
    };

    setTimeout(() => {
      this.setState({
        count: this.props.api.getModel().rowsToDisplay.length,
      });
    });
  }

  render() {
    return (
      <div className="ag-status-name-value">
        <span className="component">Row Count Component&nbsp;</span>
        <span className="ag-status-name-value-value">{this.state.count}</span>
      </div>
    );
  }
}
