// doc-pages/component-cell-renderer/examples/get-cell-renderer/_gen/modules/angular/app/medal-cell-renderer.component.ts
import { Component } from "@angular/core";
import { ICellRendererAngularComp } from "@ag-grid-community/angular";
import { ICellRendererParams } from "@ag-grid-community/core";

@Component({
  selector: "medal-component",
  template: `<span>{{ this.displayValue }}</span>`,
})
export class MedalCellRenderer implements ICellRendererAngularComp {
  private params!: ICellRendererParams;
  public displayValue!: string;

  agInit(params: ICellRendererParams): void {
    this.params = params;
    this.displayValue = new Array(params.value).fill("#").join("");
  }

  medalUserFunction() {
    console.log(
      `user function called for medal column: row = ${
        this.params.rowIndex
      }, column = ${this.params.column!.getId()}`
    );
  }
  refresh(params: ICellRendererParams) {
    return false;
  }
}

// doc-pages/component-cell-renderer/examples/get-cell-renderer/_gen/packages/reactFunctionalTs/medalCellRenderer.tsx
import React, { forwardRef, useImperativeHandle } from 'react';
import { ICellRendererParams } from 'ag-grid-community';

export default forwardRef((props: ICellRendererParams, ref) => {
  useImperativeHandle(ref, () => {
    return {
      medalUserFunction() {
        console.log(
          `user function called for medal column: row = ${
            props.rowIndex
          }, column = ${props.column?.getId()}`
        );
      },
    };
  });

  return <span>{new Array(props.value).fill('#').join('')}</span>;
});
