// doc-pages/component-cell-editor/examples/component-editor-2/_gen/packages/angular/app/mood-editor.component.ts
import { AfterViewInit, Component, ViewChild, ViewContainerRef } from '@angular/core';
import { ICellEditorAngularComp } from 'ag-grid-angular';

@Component({
    selector: 'editor-cell',
    template: `
        <div #container class="mood" tabindex="0" (keydown)="onKeyDown($event)">
            <img src="https://www.ag-grid.com/example-assets/smileys/happy.png" (click)="onClick(true)" [ngClass]="{'selected' : happy, 'default' : !happy}">
            <img src="https://www.ag-grid.com/example-assets/smileys/sad.png" (click)="onClick(false)"
                 [ngClass]="{'selected' : !happy, 'default' : happy}">
        </div>
    `,
    styles: [`
        .mood {
            border-radius: 15px;
            border: 1px solid grey;
            background: #e6e6e6;
            padding: 15px;
            text-align: center;
            display: inline-block;
            outline: none
        }

        .default {
            padding-left: 10px;
            padding-right: 10px;
            border: 1px solid transparent;
            padding: 4px;
        }

        .selected {
            padding-left: 10px;
            padding-right: 10px;
            border: 1px solid lightgreen;
            padding: 4px;
        }
    `]
})
export class MoodEditor implements ICellEditorAngularComp, AfterViewInit {
    private params: any;

    @ViewChild('container', { read: ViewContainerRef }) public container!: ViewContainerRef;
    public happy = false;

    // dont use afterGuiAttached for post gui events - hook into ngAfterViewInit instead for this
    ngAfterViewInit() {
        window.setTimeout(() => {
            this.container.element.nativeElement.focus();
        });
    }

    agInit(params: any): void {
        this.params = params;
        this.setHappy(params.value === "Happy");
    }

    getValue(): any {
        return this.happy ? "Happy" : "Sad";
    }

    isPopup(): boolean {
        return true;
    }

    setHappy(happy: boolean): void {
        this.happy = happy;
    }

    toggleMood(): void {
        this.setHappy(!this.happy);
    }

    onClick(happy: boolean) {
        this.setHappy(happy);
        this.params.api.stopEditing();
    }

    onKeyDown(event: any): void {
        const key = event.key;
        if (key == 'ArrowLeft' ||  // left
            key == 'ArrowRight') {  // right
            this.toggleMood();
            event.stopPropagation();
        }
    }
}

// doc-pages/component-cell-editor/examples/component-editor-2/_gen/packages/react/moodEditor.jsx
import React, { Component } from 'react';
import ReactDOM from 'react-dom';

export default class MoodEditor extends Component {
  constructor(props) {
    super(props);

    this.onHappyClick = this.onHappyClick.bind(this);
    this.onSadClick = this.onSadClick.bind(this);

    this.state = {
      happy: false,
    };
  }

  componentWillMount() {
    this.setHappy(this.props.value === 'Happy');
  }

  componentDidMount() {
    this.refs.container.addEventListener(
      'keydown',
      this.checkAndToggleMoodIfLeftRight
    );
    this.focus();
  }

  componentWillUnmount() {
    this.refs.container.removeEventListener(
      'keydown',
      this.checkAndToggleMoodIfLeftRight
    );
  }

  checkAndToggleMoodIfLeftRight = (event) => {
    if (['ArrowLeft', 'ArrowRight'].indexOf(event.key) > -1) {
      // left and right
      this.toggleMood();
      event.stopPropagation();
    }
  };

  componentDidUpdate() {
    this.focus();
  }

  focus() {
    window.setTimeout(() => {
      let container = ReactDOM.findDOMNode(this.refs.container);
      if (container) {
        container.focus();
      }
    }, 10);
  }

  getValue() {
    // renderer is updated but not re-rendered in grid
    return this.state.happy ? 'Happy' : 'Sad';
  }

  isPopup() {
    return true;
  }

  setHappy(happy) {
    this.setState({
      happy,
    });
  }

  onHappyClick() {
    this.setState(
      {
        happy: true,
      },
      () => this.props.api.stopEditing()
    );
  }

  onSadClick() {
    this.setState(
      {
        happy: false,
      },
      () => this.props.api.stopEditing()
    );
  }

  toggleMood() {
    this.setHappy(!this.state.happy);
  }

  render() {
    let mood = {
      borderRadius: 15,
      border: '1px solid grey',
      background: '#e6e6e6',
      padding: 15,
      textAlign: 'center',
      display: 'inline-block',
    };

    let unselected = {
      paddingLeft: 10,
      paddingRight: 10,
      border: '1px solid transparent',
      padding: 4,
    };

    let selected = {
      paddingLeft: 10,
      paddingRight: 10,
      border: '1px solid lightgreen',
      padding: 4,
    };

    let happyStyle = this.state.happy ? selected : unselected;
    let sadStyle = !this.state.happy ? selected : unselected;

    return (
      <div
        ref="container"
        style={mood}
        tabIndex={1} // important - without this the keypresses wont be caught
      >
        <img
          src="https://www.ag-grid.com/example-assets/smileys/happy.png"
          onClick={this.onHappyClick}
          style={happyStyle}
        />
        <img
          src="https://www.ag-grid.com/example-assets/smileys/sad.png"
          onClick={this.onSadClick}
          style={sadStyle}
        />
      </div>
    );
  }
}
