// doc-pages/component-cell-editor/examples/get-editor-instance/_gen/packages/reactFunctionalTs/mySimpleEditor.tsx
import { ICellEditorParams } from 'ag-grid-community';
import { ICellEditorReactComp } from 'ag-grid-react';
import React, {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
} from 'react';

const KEY_BACKSPACE = 'Backspace';
const KEY_DELETE = 'Delete';

export interface MySimpleInterface extends ICellEditorReactComp {
  myCustomFunction(): { rowIndex: number; colId: string };
}

export default forwardRef((props: ICellEditorParams, ref) => {
  const getInitialValue = (props: ICellEditorParams) => {
    let startValue = props.value;

    const isBackspaceOrDelete =
      props.eventKey === KEY_BACKSPACE || props.eventKey === KEY_DELETE;
    if (isBackspaceOrDelete) {
      startValue = '';
    } else if (props.charPress) {
      startValue = props.charPress;
    }

    if (startValue !== null && startValue !== undefined) {
      return startValue;
    }

    return '';
  };

  const [value, setValue] = useState(getInitialValue(props));
  const refInput = useRef<HTMLInputElement>(null);

  useEffect(() => {
    refInput.current!.focus();
  }, []);

  useImperativeHandle(ref, () => {
    return {
      getValue() {
        return value;
      },

      myCustomFunction() {
        return {
          rowIndex: props.rowIndex,
          colId: props.column.getId(),
        };
      },
    };
  });

  return (
    <input
      value={value}
      ref={refInput}
      onChange={(event) => setValue(event.target.value)}
    />
  );
});

// doc-pages/component-cell-editor/examples/get-editor-instance/_gen/packages/angular/app/mySimple-editor.component.ts
import {
  AfterViewInit,
  Component,
  ViewChild,
  ViewContainerRef,
} from "@angular/core";
import { ICellEditorParams } from "ag-grid-community";
import { ICellEditorAngularComp } from "ag-grid-angular";

const KEY_BACKSPACE = "Backspace";
const KEY_DELETE = "Delete";

@Component({
  selector: "editor-cell",
  template: `<input class="my-simple-editor" [value]="value" #input /> `,
})
export class MySimpleEditor implements ICellEditorAngularComp, AfterViewInit {
  private params!: ICellEditorParams;
  public value: any;

  @ViewChild("input", { read: ViewContainerRef })
  public input!: ViewContainerRef;

  agInit(params: ICellEditorParams): void {
    this.params = params;

    this.value = this.getInitialValue(params);
  }

  getValue(): any {
    return this.value;
  }

  getInitialValue(params: ICellEditorParams): any {
    let startValue = params.value;

    const isBackspaceOrDelete =
      params.eventKey === KEY_BACKSPACE || params.eventKey === KEY_DELETE;
    if (isBackspaceOrDelete) {
      startValue = "";
    } else if (params.charPress) {
      startValue = params.charPress;
    }

    if (startValue !== null && startValue !== undefined) {
      return startValue;
    }

    return "";
  }

  myCustomFunction() {
    return {
      rowIndex: this.params.rowIndex,
      colId: this.params.column.getId(),
    };
  }

  ngAfterViewInit() {
    setTimeout(() => {
      this.input.element.nativeElement.focus();
    });
  }
}
