// doc-pages/component-cell-renderer/examples/simple/_gen/packages/angular/app/total-value-renderer.component.ts
import { Component } from '@angular/core';
import { ICellRendererAngularComp } from 'ag-grid-angular';
import { ICellRendererParams } from 'ag-grid-community';


@Component({
    selector: 'total-value-component',
    template: `
          <span>
              <span>{{cellValue}}</span>&nbsp;
              <button (click)="buttonClicked()">Push For Total</button>
          </span>
    `
})
export class TotalValueRenderer implements ICellRendererAngularComp {
    public cellValue!: string;

    // gets called once before the renderer is used
    agInit(params: ICellRendererParams): void {
        this.cellValue = this.getValueToDisplay(params);
    }

    // gets called whenever the user gets the cell to refresh
    refresh(params: ICellRendererParams) {
        // set value into cell again
        this.cellValue = this.getValueToDisplay(params);
        return true;
    }

    buttonClicked() {
        alert(`${this.cellValue} medals won!`)
    }

    getValueToDisplay(params: ICellRendererParams) {
        return params.valueFormatted ? params.valueFormatted : params.value;
    }
}

// doc-pages/component-cell-renderer/examples/simple/_gen/modules/reactFunctionalTs/totalValueRenderer.tsx
import React from 'react';
import { ICellRendererParams } from '@ag-grid-community/core';

export default (props: ICellRendererParams) => {
  const cellValue = props.valueFormatted ? props.valueFormatted : props.value;

  const buttonClicked = () => {
    alert(`${cellValue} medals won!`);
  };

  return (
    <span>
      <span>{cellValue}</span>&nbsp;
      <button onClick={() => buttonClicked()}>Push For Total</button>
    </span>
  );
};
