// doc-pages/master-detail-other/examples/embed-custom-detail/_gen/modules/reactFunctionalTs/detailCellRenderer.tsx
import React, { Component } from 'react';
import { ICellRendererParams } from '@ag-grid-community/core';

export default class DetailCellRenderer extends Component<
  ICellRendererParams,
  { pinned: string | null | undefined }
> {
  constructor(props: ICellRendererParams) {
    super(props);

    this.state = {
      pinned: props.pinned,
    };
  }

  render() {
    return (
      <h1 className="custom-detail" style={{ padding: '20px' }}>
        {this.state.pinned ? this.state.pinned : 'center'}
      </h1>
    );
  }
}

// doc-pages/master-detail-custom-detail/examples/simple-custom-detail/_gen/modules/angular/app/detail-cell-renderer.component.ts
import { ICellRendererAngularComp } from "@ag-grid-community/angular";
import { Component } from "@angular/core";

@Component({
  selector: "app-detail-cell-renderer",
  template: `<h1 style="padding: 20px;">My Custom Detail</h1>`,
})
export class DetailCellRenderer implements ICellRendererAngularComp {
  agInit(params: any): void {}

  refresh(params: any): boolean {
    return false;
  }
}
