// doc-pages/component-header/examples/header-component/_gen/modules/angular/app/custom-header.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { IHeaderAngularComp } from '@ag-grid-community/angular';
import { IHeaderParams } from '@ag-grid-community/core';

export interface ICustomHeaderParams {
    menuIcon: string;
}

@Component({
    selector: 'app-custom-header',
    template: `
      <div>
      <div *ngIf="params.enableMenu" #menuButton class="customHeaderMenuButton" (click)="onMenuClicked($event)"><i class="fa {{params.menuIcon}}"></i>
      </div>
      <div class="customHeaderLabel">{{ params.displayName }}</div>
      <div *ngIf="params.enableSorting" (click)="onSortRequested('asc', $event)" [ngClass]="ascSort" class="customSortDownLabel"><i
          class="fa fa-long-arrow-alt-down"></i></div>
      <div *ngIf="params.enableSorting" (click)="onSortRequested('desc', $event)" [ngClass]="descSort" class="customSortUpLabel"><i
          class="fa fa-long-arrow-alt-up"></i></div>
      <div *ngIf="params.enableSorting" (click)="onSortRequested('', $event)" [ngClass]="noSort" class="customSortRemoveLabel"><i
          class="fa fa-times"></i></div>
      </div>
    `,
    styles: [
        `
            .customHeaderMenuButton,
            .customHeaderLabel,
            .customSortDownLabel,
            .customSortUpLabel,
            .customSortRemoveLabel {
                float: left;
                margin: 0 0 0 3px;
            }

            .customSortUpLabel {
                margin: 0;
            }

            .customSortRemoveLabel {
                font-size: 11px;
            }

            .active {
                color: cornflowerblue;
            }
        `
    ]
})
export class CustomHeader implements IHeaderAngularComp {
    public params!: IHeaderParams & ICustomHeaderParams;

    public ascSort = 'inactive';
    public descSort = 'inactive';
    public noSort = 'inactive';

    @ViewChild('menuButton', { read: ElementRef }) public menuButton!: ElementRef;

    agInit(params: IHeaderParams & ICustomHeaderParams): void {
        this.params = params;

        params.column.addEventListener('sortChanged', this.onSortChanged.bind(this));

        this.onSortChanged();
    }

    onMenuClicked() {
        this.params.showColumnMenu(this.menuButton.nativeElement);
    }

    onSortChanged() {
        this.ascSort = this.descSort = this.noSort = 'inactive';
        if (this.params.column.isSortAscending()) {
            this.ascSort = 'active';
        } else if (this.params.column.isSortDescending()) {
            this.descSort = 'active';
        } else {
            this.noSort = 'active';
        }
    }

    onSortRequested(order: 'asc' | 'desc' | null, event: any) {
        this.params.setSort(order, event.shiftKey);
    }

    refresh(params: IHeaderParams) {
        return false;
    }
}

// doc-pages/component-header/examples/header-component/_gen/packages/react/customHeader.jsx
import React, { Component } from "react";

export default class CustomHeader extends Component {
  constructor(props) {
    super(props);

    this.state = {
      ascSort: "inactive",
      descSort: "inactive",
      noSort: "inactive",
    };

    props.column.addEventListener("sortChanged", this.onSortChanged.bind(this));
  }

  componentDidMount() {
    this.onSortChanged();
  }

  render() {
    let menu = null;
    if (this.props.enableMenu) {
      menu = (
        <div
          ref={(menuButton) => {
            this.menuButton = menuButton;
          }}
          className="customHeaderMenuButton"
          onClick={this.onMenuClicked.bind(this)}
        >
          <i className={`fa ${this.props.menuIcon}`}></i>
        </div>
      );
    }

    let sort = null;
    if (this.props.enableSorting) {
      sort = (
        <div style={{ display: "inline-block" }}>
          <div
            onClick={this.onSortRequested.bind(this, "asc")}
            onTouchEnd={this.onSortRequested.bind(this, "asc")}
            className={`customSortDownLabel ${this.state.ascSort}`}
          >
            <i class="fa fa-long-arrow-alt-down"></i>
          </div>
          <div
            onClick={this.onSortRequested.bind(this, "desc")}
            onTouchEnd={this.onSortRequested.bind(this, "desc")}
            className={`customSortUpLabel ${this.state.descSort}`}
          >
            <i class="fa fa-long-arrow-alt-up"></i>
          </div>
          <div
            onClick={this.onSortRequested.bind(this, "")}
            onTouchEnd={this.onSortRequested.bind(this, "")}
            className={`customSortRemoveLabel ${this.state.noSort}`}
          >
            <i class="fa fa-times"></i>
          </div>
        </div>
      );
    }

    return (
      <div>
        {menu}
        <div className="customHeaderLabel">{this.props.displayName}</div>
        {sort}
      </div>
    );
  }

  onMenuClicked() {
    this.props.showColumnMenu(this.menuButton);
  }

  onSortChanged() {
    this.setState({
      ascSort: this.props.column.isSortAscending() ? "active" : "inactive",
      descSort: this.props.column.isSortDescending() ? "active" : "inactive",
      noSort:
        !this.props.column.isSortAscending() &&
        !this.props.column.isSortDescending()
          ? "active"
          : "inactive",
    });
  }

  onSortRequested(order, event) {
    this.props.setSort(order, event.shiftKey);
  }
}
