// doc-pages/component-loading-cell-renderer/examples/custom-loading-cell-renderer/_gen/packages/reactFunctionalTs/customLoadingCellRenderer.tsx
import React from 'react';
import { ILoadingCellRendererParams } from 'ag-grid-community';

export default (
  props: ILoadingCellRendererParams & { loadingMessage: string }
) => {
  return (
    <div
      className="ag-custom-loading-cell"
      style={{ paddingLeft: '10px', lineHeight: '25px' }}
    >
      <i className="fas fa-spinner fa-pulse"></i>{' '}
      <span> {props.loadingMessage}</span>
    </div>
  );
};

// doc-pages/component-loading-cell-renderer/examples/custom-loading-cell-renderer/_gen/modules/angular/app/custom-loading-cell-renderer.component.ts
import { ILoadingCellRendererAngularComp } from '@ag-grid-community/angular';
import { ILoadingCellRendererParams } from '@ag-grid-community/core';
import { Component } from '@angular/core';

@Component({
  selector: 'app-loading-cell-renderer',
  template: `
    <div
      class="ag-custom-loading-cell"
      style="padding-left: 10px; line-height: 25px;"
    >
      <i class="fas fa-spinner fa-pulse"></i>
      <span> {{ params.loadingMessage }} </span>
    </div>
  `,
})
export class CustomLoadingCellRenderer
  implements ILoadingCellRendererAngularComp {
  public params!: ILoadingCellRendererParams & { loadingMessage: string };

  agInit(
    params: ILoadingCellRendererParams & { loadingMessage: string }
  ): void {
    this.params = params;
  }
}
