// doc-pages/component-cell-renderer/examples/simple/_gen/modules/react/totalValueRenderer.jsx
import React, { Component } from 'react';

export default class TotalValueRenderer extends Component {
  constructor(props) {
    super(props);

    this.state = {
      cellValue: TotalValueRenderer.getValueToDisplay(props),
    };
  }

  // update cellValue when the cell's props are updated
  static getDerivedStateFromProps(nextProps) {
    return {
      cellValue: TotalValueRenderer.getValueToDisplay(nextProps),
    };
  }

  buttonClicked() {
    alert(`${this.state.cellValue} medals won!`);
  }

  render() {
    return (
      <span>
        <span>{this.state.cellValue}</span>&nbsp;
        <button onClick={() => this.buttonClicked()}>Push For Total</button>
      </span>
    );
  }

  static getValueToDisplay(params) {
    return params.valueFormatted ? params.valueFormatted : params.value;
  }
}

// doc-pages/component-cell-renderer/examples/simple/_gen/modules/angular/app/total-value-renderer.component.ts
import { ICellRendererAngularComp } from '@ag-grid-community/angular';
import { ICellRendererParams } from '@ag-grid-community/core';
import { Component } from '@angular/core';

@Component({
  selector: 'total-value-component',
  template: `
    <span>
      <span>{{ cellValue }}</span
      >&nbsp;
      <button (click)="buttonClicked()">Push For Total</button>
    </span>
  `,
})
export class TotalValueRenderer implements ICellRendererAngularComp {
  public cellValue!: string;

  // gets called once before the renderer is used
  agInit(params: ICellRendererParams): void {
    this.cellValue = this.getValueToDisplay(params);
  }

  // gets called whenever the user gets the cell to refresh
  refresh(params: ICellRendererParams) {
    // set value into cell again
    this.cellValue = this.getValueToDisplay(params);
    return true;
  }

  buttonClicked() {
    alert(`${this.cellValue} medals won!`);
  }

  getValueToDisplay(params: ICellRendererParams) {
    return params.valueFormatted ? params.valueFormatted : params.value;
  }
}
