// doc-pages/column-moving/examples/advanced-lock/_gen/packages/angular/app/controls-cell-renderer.component.ts
import { Component } from "@angular/core";
import { ICellRendererAngularComp } from "ag-grid-angular";
import { ICellRendererParams } from "ag-grid-community";

// simple cell renderer returns dummy buttons. in a real application, a component would probably
// be used with operations tied to the buttons. in this example, the cell renderer is just for
// display purposes.
@Component({
  selector: "simple-component",
  template: `
    <button>A</button>
    <button>B</button>
    <button>C</button>
  `,
})
export class ControlsCellRenderer implements ICellRendererAngularComp {
  private params!: ICellRendererParams;
  agInit(params: ICellRendererParams): void {
    this.params = params;
  }

  refresh(params: ICellRendererParams) {
    return false;
  }
}

// doc-pages/column-moving/examples/advanced-lock/_gen/packages/react/controlsCellRenderer.jsx
import React, { Component } from "react";

// simple cell renderer returns dummy buttons. in a real application, a component would probably
// be used with operations tied to the buttons. in this example, the cell renderer is just for
// display purposes.
export default class ControlsComponent extends Component {
  render() {
    return (
      <React.Fragment>
        <button>A</button>
        <button>B</button>
        <button>C</button>
      </React.Fragment>
    );
  }
}
