// doc-pages/excel-export-images/examples/excel-export-cells-with-images-text/_gen/modules/angular/app/country-cell-renderer.component.ts
import { ICellRendererAngularComp } from '@ag-grid-community/angular';
import { ICellRendererParams } from '@ag-grid-community/core';
import { Component } from '@angular/core';

// simple cell renderer returns dummy buttons. in a real application, a component would probably
// be used with operations tied to the buttons. in this example, the cell renderer is just for
// display purposes.
@Component({
  selector: 'simple-component',
  template: `<img
    alt="{{ params.data.country }}"
    src="{{
      params.context.base64flags[
        params.context.countryCodes[params.data.country]
      ]
    }}"
  />`,
})
export class CountryCellRenderer implements ICellRendererAngularComp {
  private params!: ICellRendererParams;

  agInit(params: ICellRendererParams): void {
    this.params = params;
  }

  refresh() {
    return false;
  }
}

// doc-pages/excel-export-images/examples/excel-export-cells-with-images-text/_gen/modules/react/countryCellRenderer.jsx
import React, { Component } from 'react';

// simple cell renderer returns dummy buttons. in a real application, a component would probably
// be used with operations tied to the buttons. in this example, the cell renderer is just for
// display purposes.
export default class ControlsComponent extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <React.Fragment>
        <img
          alt={this.props.data.country}
          src={
            this.props.context.base64flags[
              this.props.context.countryCodes[this.props.data.country]
            ]
          }
        />
      </React.Fragment>
    );
  }
}
