// doc-pages/component-floating-filter/examples/custom-filter-and-floating-filter/_gen/packages/angular/app/number-filter-component.component.ts
import { Component } from '@angular/core';
import { IFilterAngularComp } from 'ag-grid-angular';
import { IDoesFilterPassParams, IFilterParams } from 'ag-grid-community';

@Component({
  selector: 'number-component',
  template: `
    <div style="padding: 4px">
      <div style="font-weight: bold;">Greater than:</div>
      <div>
        <input
          style="margin: 4px 0 4px 0;"
          type="number"
          [(ngModel)]="filterText"
          (input)="onInputBoxChanged($event)"
          placeholder="Number of medals..."
        />
      </div>
    </div>
  `,
})
export class NumberFilterComponent implements IFilterAngularComp {
  params!: IFilterParams;
  filterText: number | null | string = null;

  agInit(params: IFilterParams): void {
    this.params = params;
  }

  doesFilterPass(params: IDoesFilterPassParams) {
    if (!this.isFilterActive()) {
      return true;
    }

    var { api, colDef, column, columnApi, context, valueGetter } = this.params;
    var { node } = params;

    var value = valueGetter({
      api,
      colDef,
      column,
      columnApi,
      context,
      data: node.data,
      getValue: (field) => node.data[field],
      node,
    });

    if (!value) return false;
    return Number(value) > Number(this.filterText);
  }

  isFilterActive() {
    return (
      this.filterText !== null &&
      this.filterText !== undefined &&
      this.filterText !== '' &&
      this.isNumeric(this.filterText)
    );
  }

  isNumeric(n: any) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  }

  getModel() {
    return this.isFilterActive() ? Number(this.filterText) : null;
  }

  setModel(model: any) {
    this.filterText = model;
    this.params.filterChangedCallback();
  }

  myMethodForTakingValueFromFloatingFilter(value: any) {
    this.filterText = value;
    this.params.filterChangedCallback();
  }

  onInputBoxChanged() {
    this.params.filterChangedCallback();
  }
}

// doc-pages/component-floating-filter/examples/custom-filter-and-floating-filter/_gen/modules/reactFunctionalTs/numberFilterComponent.tsx
import React, {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
} from 'react';
import { IDoesFilterPassParams, IFilterParams } from '@ag-grid-community/core';

export default forwardRef((props: IFilterParams, ref) => {
  const [filterText, setFilterText] = useState<string | null>(null);
  const inputRef = useRef<any>(null);

  const isNumeric = (n: string) =>
    !isNaN(parseFloat(n)) && isFinite(parseFloat(n));

  useEffect(() => {
    if (inputRef.current) {
      inputRef.current.value = filterText;
    }
    props.filterChangedCallback();
  }, [filterText]);

  const isFilterActive = () => {
    return (
      filterText !== null &&
      filterText !== undefined &&
      filterText !== '' &&
      isNumeric(filterText)
    );
  };

  // expose AG Grid Filter Lifecycle callbacks
  useImperativeHandle(ref, () => {
    return {
      isFilterActive,

      doesFilterPass(params: IDoesFilterPassParams) {
        if (!this.isFilterActive()) {
          return;
        }

        const { api, colDef, column, columnApi, context, valueGetter } = props;
        const { node } = params;

        const value = valueGetter({
          api,
          colDef,
          column,
          columnApi,
          context,
          data: node.data,
          getValue: (field) => node.data[field],
          node,
        });

        if (!value) return false;
        return Number(value) > Number(filterText);
      },

      getModel() {
        return isFilterActive() ? Number(filterText) : null;
      },

      setModel(model: any) {
        setFilterText(model);
      },

      myMethodForTakingValueFromFloatingFilter(value: string) {
        setFilterText(value);
      },
    };
  });

  const onInputBoxChanged = (event: any) => {
    setFilterText(event.target.value);
  };

  return (
    <div style={{ padding: '4px' }}>
      <div style={{ fontWeight: 'bold' }}>Greater than:</div>
      <div>
        <input
          ref={inputRef}
          style={{ margin: '4px 0 4px 0' }}
          type="number"
          onInput={onInputBoxChanged}
          placeholder="Number of medals..."
        />
      </div>
    </div>
  );
});
