// doc-pages/component-cell-editor/examples/get-editor-instance/_gen/packages/react/mySimpleEditor.jsx
import React, { Component, createRef } from "react";

const KEY_BACKSPACE = "Backspace";
const KEY_DELETE = "Delete";

export default class MySimpleEditor extends Component {
  constructor(props) {
    super(props);

    this.inputRef = createRef();

    this.state = {
      value: this.getInitialValue(props),
    };
  }

  componentDidMount() {
    setTimeout(() => this.inputRef.current.focus());
  }

  getInitialValue(props) {
    let startValue = props.value;

    const isBackspaceOrDelete =
      props.key === KEY_BACKSPACE || props.key === KEY_DELETE;
    if (isBackspaceOrDelete) {
      startValue = "";
    } else if (props.charPress) {
      startValue = props.charPress;
    }

    if (startValue !== null && startValue !== undefined) {
      return startValue;
    }

    return "";
  }

  getValue() {
    return this.state.value;
  }

  myCustomFunction() {
    return {
      rowIndex: this.props.rowIndex,
      colId: this.props.column.getId(),
    };
  }

  render() {
    return (
      <input
        value={this.state.value}
        ref={this.inputRef}
        onChange={(event) => this.setState({ value: event.target.value })}
      />
    );
  }
}

// doc-pages/component-cell-editor/examples/get-editor-instance/_gen/modules/angular/app/mySimple-editor.component.ts
import { ICellEditorAngularComp } from "@ag-grid-community/angular";
import { ICellEditorParams } from "@ag-grid-community/core";
import {
  AfterViewInit,
  Component,
  ViewChild,
  ViewContainerRef,
} from "@angular/core";

const KEY_BACKSPACE = "Backspace";
const KEY_DELETE = "Delete";

@Component({
  selector: "editor-cell",
  template: `<input class="my-simple-editor" [value]="value" #input /> `,
})
export class MySimpleEditor implements ICellEditorAngularComp, AfterViewInit {
  private params!: ICellEditorParams;
  public value: any;

  @ViewChild("input", { read: ViewContainerRef })
  public input!: ViewContainerRef;

  agInit(params: ICellEditorParams): void {
    this.params = params;

    this.value = this.getInitialValue(params);
  }

  getValue(): any {
    return this.value;
  }

  getInitialValue(params: ICellEditorParams): any {
    let startValue = params.value;

    const isBackspaceOrDelete =
      params.eventKey === KEY_BACKSPACE || params.eventKey === KEY_DELETE;
    if (isBackspaceOrDelete) {
      startValue = "";
    } else if (params.charPress) {
      startValue = params.charPress;
    }

    if (startValue !== null && startValue !== undefined) {
      return startValue;
    }

    return "";
  }

  myCustomFunction() {
    return {
      rowIndex: this.params.rowIndex,
      colId: this.params.column.getId(),
    };
  }

  ngAfterViewInit() {
    setTimeout(() => {
      this.input.element.nativeElement.focus();
    });
  }
}
