// doc-pages/grouping-group-rows/examples/full-width-groups-rendering/_gen/packages/reactFunctionalTs/groupRowInnerRenderer.tsx
import { ICellRendererParams } from 'ag-grid-community';
import React, { useEffect, useState } from 'react';

interface GroupFlagCellRendererParams extends ICellRendererParams {
  flagCodes: Record<string, string>;
}

export default (props: GroupFlagCellRendererParams) => {
  const node = props.node;
  const aggData = node.aggData;
  const flagCode = props.flagCodes[node.key || ''];

  const [flagCodeImg, setFlagCodeImg] = useState(
    `https://flags.fmcdn.net/data/flags/mini/${flagCode}.png`
  );
  const [countryName, setCountryName] = useState(node.key);
  const [goldCount, setGoldCount] = useState(aggData.gold);
  const [silverCount, setSilverCount] = useState(aggData.silver);
  const [bronzeCount, setBronzeCount] = useState(aggData.bronze);

  const refreshUi = () => {
    const node = props.node;
    const aggData = node.aggData;
    const flagCode = props.flagCodes[node.key || ''];

    setFlagCodeImg(`https://flags.fmcdn.net/data/flags/mini/${flagCode}.png`);
    setCountryName(node.key);
    setGoldCount(aggData.gold);
    setSilverCount(aggData.silver);
    setBronzeCount(aggData.bronze);
  };

  const dataChangedListener = () => refreshUi();

  useEffect(() => {
    props.api.addEventListener('cellValueChanged', dataChangedListener);
    props.api.addEventListener('filterChanged', dataChangedListener);

    return () => {
      props.api.removeEventListener('cellValueChanged', dataChangedListener);
      props.api.removeEventListener('filterChanged', dataChangedListener);
    };
  }, []);

  let img: any = '';
  if (flagCode) {
    img = <img className="flag" width="20" height="15" src={flagCodeImg} />;
  }

  return (
    <div style={{ display: 'inline-block' }}>
      {img}
      <span className="groupTitle">{countryName}</span>
      <span
        className="medal gold"
        aria-label={`${countryName} - ${goldCount} gold medals`}
      >
        <i className="fas fa-medal"></i>
        {goldCount}
      </span>
      <span
        className="medal silver"
        aria-label={`${countryName} - ${silverCount} silver medals`}
      >
        <i className="fas fa-medal"></i>
        {silverCount}
      </span>
      <span
        className="medal bronze"
        aria-label={`${countryName} - ${bronzeCount} bronze medals`}
      >
        <i className="fas fa-medal"></i>
        {bronzeCount}
      </span>
    </div>
  );
};

// doc-pages/grouping-group-rows/examples/full-width-groups-rendering/_gen/modules/angular/app/group-row-inner-renderer.component.ts
import { ICellRendererAngularComp } from '@ag-grid-community/angular';
import { GroupCellRendererParams, RowNode } from '@ag-grid-community/core';
import { Component } from '@angular/core';

interface GroupRowParams extends GroupCellRendererParams {
  flagCodes: Record<string, string>;
}

@Component({
  selector: 'group-row-cell',
  template: ` <div class="row">
    <img
      *ngIf="flagCode"
      class="flag"
      border="0"
      width="20"
      height="15"
      [src]="flagCodeImg"
    />
    <span class="groupTitle">{{ node.key }}</span>
    <span
      class="medal gold"
      attr.aria-label="{{ node.key }} - {{ node.aggData.gold }} gold medals"
      ><i class="fas fa-medal"></i>{{ node.aggData.gold }}</span
    >
    <span
      class="medal silver"
      attr.aria-label="{{ node.key }} - {{ node.aggData.silver }} silver medals"
      ><i class="fas fa-medal"></i>{{ node.aggData.silver }}</span
    >
    <span
      class="medal bronze"
      attr.aria-label="{{ node.key }} - {{ node.aggData.bronze }} bronze medals"
      ><i class="fas fa-medal"></i>{{ node.aggData.bronze }}</span
    >
  </div>`,
  styles: [
    `
      .row {
        display: inline-block;
      }

      .groupTitle {
        font-size: 16px;
        font-weight: bold;
      }

      .medal {
        margin: 0 5px;
      }

      .gold {
        color: #e4ab11;
      }

      .silver {
        color: #bbb4bb;
      }

      .bronze {
        color: #be9088;
      }

      .flag {
        margin: 0 4px;
        position: relative;
        top: 2px;
      }
    `,
  ],
})
export class GroupRowInnerRenderer implements ICellRendererAngularComp {
  public flagCodeImg!: string;
  public flagCode!: any;
  public node!: RowNode;

  agInit(params: GroupRowParams): void {
    this.node = params.node;
    this.flagCode = params.flagCodes[params.node.key || ''];
    this.flagCodeImg = `https://flags.fmcdn.net/data/flags/mini/${this.flagCode}.png`;
  }

  refresh(): boolean {
    return false;
  }
}
