// doc-pages/component-overlay/examples/custom-overlay-components/_gen/packages/reactFunctionalTs/customLoadingOverlay.tsx
import React from 'react';
import { ICellRendererParams } from 'ag-grid-community';

export default (props: ICellRendererParams & { loadingMessage: string }) => {
  return (
    <div
      className="ag-overlay-loading-center"
      style={{ backgroundColor: 'lightsteelblue', height: '9%' }}
    >
      <i className="fas fa-hourglass-half"> {props.loadingMessage} </i>
    </div>
  );
};

// doc-pages/component-overlay/examples/custom-overlay-components/_gen/modules/angular/app/custom-loading-overlay.component.ts
import { ILoadingOverlayAngularComp } from '@ag-grid-community/angular';
import { ILoadingOverlayParams } from '@ag-grid-community/core';
import { Component } from '@angular/core';

@Component({
  selector: 'app-loading-overlay',
  template: `
    <div
      class="ag-overlay-loading-center"
      style="background-color: lightsteelblue;"
    >
      <i class="fas fa-hourglass-half">{{ params.loadingMessage }} </i>
    </div>
  `,
})
export class CustomLoadingOverlay implements ILoadingOverlayAngularComp {
  public params!: ILoadingOverlayParams & { loadingMessage: string };

  agInit(params: ILoadingOverlayParams & { loadingMessage: string }): void {
    this.params = params;
  }
}
