// doc-pages/component-overlay/examples/custom-overlay-components/_gen/packages/reactFunctionalTs/customNoRowsOverlay.tsx
import React from 'react';
import { ICellRendererParams } from 'ag-grid-community';

export default (
  props: ICellRendererParams & { noRowsMessageFunc: () => string }
) => {
  return (
    <div
      className="ag-overlay-loading-center"
      style={{ backgroundColor: 'lightcoral', height: '9%' }}
    >
      <i className="far fa-frown"> {props.noRowsMessageFunc()}</i>
    </div>
  );
};

// doc-pages/component-overlay/examples/custom-overlay-components/_gen/modules/angular/app/custom-no-rows-overlay.component.ts
import { INoRowsOverlayAngularComp } from "@ag-grid-community/angular";
import { INoRowsOverlayParams } from "@ag-grid-community/core";
import { Component } from "@angular/core";

@Component({
  selector: "app-no-rows-overlay",
  template: ` <div
    class="ag-overlay-loading-center"
    style="background-color: lightcoral;"
  >
    <i class="far fa-frown"> {{ this.params.noRowsMessageFunc() }} </i>
  </div>`,
})
export class CustomNoRowsOverlay implements INoRowsOverlayAngularComp {
  public params!: INoRowsOverlayParams & { noRowsMessageFunc: () => string };

  agInit(
    params: INoRowsOverlayParams & { noRowsMessageFunc: () => string }
  ): void {
    this.params = params;
  }
}
