// doc-pages/component-cell-renderer/examples/simple/_gen/modules/angular/app/medal-cell-renderer.component.ts
import { Component } from "@angular/core";
import { ICellRendererAngularComp } from "@ag-grid-community/angular";
import { ICellRendererParams } from "@ag-grid-community/core";

@Component({
  selector: "medal-component",
  template: `<span>{{ this.displayValue }}</span>`,
})
export class MedalCellRenderer implements ICellRendererAngularComp {
  public displayValue!: string;

  agInit(params: ICellRendererParams): void {
    this.displayValue = new Array(parseInt(params.value, 10))
      .fill("#")
      .join("");
  }

  refresh(params: ICellRendererParams) {
    return false;
  }
}

// doc-pages/component-cell-renderer/examples/get-cell-renderer/_gen/modules/reactFunctionalTs/medalCellRenderer.tsx
import React, { forwardRef, useImperativeHandle } from 'react';
import { ICellRendererParams } from '@ag-grid-community/core';

export default forwardRef((props: ICellRendererParams, ref) => {
  useImperativeHandle(ref, () => {
    return {
      medalUserFunction() {
        console.log(
          `user function called for medal column: row = ${
            props.rowIndex
          }, column = ${props.column?.getId()}`
        );
      },
    };
  });

  return <span>{new Array(props.value).fill('#').join('')}</span>;
});
