// doc-pages/master-detail-other/examples/embed-custom-detail/_gen/modules/angular/app/detail-cell-renderer.component.ts
import { Component } from '@angular/core';
import { ICellRendererAngularComp } from '@ag-grid-community/angular';
import { ICellRendererParams } from '@ag-grid-community/core';

@Component({
    selector: 'app-detail-cell-renderer',
    template: `<h1 class="custom-detail" style="padding: 20px;">{{pinned}}</h1>`
})
export class DetailCellRenderer implements ICellRendererAngularComp {

    public pinned!: string;

    agInit(params: ICellRendererParams): void {
        this.pinned = params.pinned ? params.pinned : 'center';
    }

    refresh(params: ICellRendererParams): boolean { return false; }
}

// doc-pages/master-detail-other/examples/embed-custom-detail/_gen/packages/reactFunctional/detailCellRenderer.jsx
import React, { Component } from "react";

export default class DetailCellRenderer extends Component {
  constructor(props) {
    super(props);

    this.state = {
      pinned: props.pinned,
    };
  }

  render() {
    return (
      <h1 class="custom-detail" style={{ padding: "20px" }}>
        {this.state.pinned ? this.state.pinned : "center"}
      </h1>
    );
  }
}
