// doc-pages/component-loading-cell-renderer/examples/custom-loading-cell-renderer/_gen/packages/angular/app/custom-loading-cell-renderer.component.ts
import { Component } from '@angular/core';
import { ILoadingCellRendererAngularComp } from 'ag-grid-angular';
import { ILoadingCellRendererParams } from 'ag-grid-community';

@Component({
  selector: 'app-loading-cell-renderer',
  template: `
      <div class="ag-custom-loading-cell" style="padding-left: 10px; line-height: 25px;">
        <i class="fas fa-spinner fa-pulse"></i>
        <span> {{ this.params.loadingMessage }} </span>
      </div>
    `
})
export class CustomLoadingCellRenderer implements ILoadingCellRendererAngularComp {
  public params!: ILoadingCellRendererParams & { loadingMessage: string };

  agInit(params: ILoadingCellRendererParams & { loadingMessage: string }): void {
    this.params = params;
  }
}

// doc-pages/component-loading-cell-renderer/examples/custom-loading-cell-renderer/_gen/modules/reactFunctionalTs/customLoadingCellRenderer.tsx
import React from 'react';
import { ILoadingCellRendererParams } from '@ag-grid-community/core';

export default (
  props: ILoadingCellRendererParams & { loadingMessage: string }
) => {
  return (
    <div
      className="ag-custom-loading-cell"
      style={{ paddingLeft: '10px', lineHeight: '25px' }}
    >
      <i className="fas fa-spinner fa-pulse"></i>{' '}
      <span> {props.loadingMessage}</span>
    </div>
  );
};
