// doc-pages/component-overlay/examples/custom-overlay-components/_gen/packages/angular/app/custom-no-rows-overlay.component.ts
import { Component } from '@angular/core';
import { INoRowsOverlayAngularComp } from 'ag-grid-angular';
import { INoRowsOverlayParams } from 'ag-grid-community';

@Component({
  selector: 'app-no-rows-overlay',
  template: ` <div
    class="ag-overlay-loading-center"
    style="background-color: lightcoral;"
  >
    <i class="far fa-frown"> {{ params.noRowsMessageFunc() }} </i>
  </div>`,
})
export class CustomNoRowsOverlay implements INoRowsOverlayAngularComp {
  public params!: INoRowsOverlayParams & { noRowsMessageFunc: () => string };

  agInit(
    params: INoRowsOverlayParams & { noRowsMessageFunc: () => string }
  ): void {
    this.params = params;
  }
}

// doc-pages/component-overlay/examples/custom-overlay-components/_gen/modules/reactFunctionalTs/customNoRowsOverlay.tsx
import React from 'react';
import { ICellRendererParams } from '@ag-grid-community/core';

export default (
  props: ICellRendererParams & { noRowsMessageFunc: () => string }
) => {
  return (
    <div
      className="ag-overlay-loading-center"
      style={{ backgroundColor: 'lightcoral', height: '9%' }}
    >
      <i className="far fa-frown"> {props.noRowsMessageFunc()}</i>
    </div>
  );
};
