// doc-pages/component-floating-filter/examples/custom-floating-filter/_gen/modules/reactFunctionalTs/numberFloatingFilterComponent.tsx
import React, {
  Fragment,
  forwardRef,
  useImperativeHandle,
  useRef,
  useState,
} from 'react';
import {
  IFloatingFilterParams,
  NumberFilterModel,
} from '@ag-grid-community/core';

export interface CustomParams extends IFloatingFilterParams {
  suppressFilterButton: boolean;
  color: string;
}

export default forwardRef((props: CustomParams, ref) => {
  const [currentValue, setCurrentValue] = useState<number | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  // expose AG Grid Filter Lifecycle callbacks
  useImperativeHandle(ref, () => {
    return {
      onParentModelChanged(parentModel: NumberFilterModel) {
        // When the filter is empty we will receive a null value here
        if (!parentModel) {
          inputRef.current!.value = '';
          setCurrentValue(null);
        } else {
          inputRef.current!.value = parentModel.filter + '';
          setCurrentValue(parentModel.filter!);
        }
      },
    };
  });

  const onInputBoxChanged = (input: any) => {
    if (input.target.value === '') {
      // Remove the filter
      props.parentFilterInstance((instance) => {
        instance.onFloatingFilterChanged(null, null);
      });
      return;
    }

    setCurrentValue(Number(input.target.value));
    props.parentFilterInstance((instance) => {
      instance.onFloatingFilterChanged('greaterThan', input.target.value);
    });
  };

  const style = {
    color: props.color,
    width: '30px',
  };

  return (
    <Fragment>
      &gt;{' '}
      <input
        ref={inputRef}
        style={style}
        type="number"
        min="0"
        onInput={onInputBoxChanged}
      />
    </Fragment>
  );
});

// doc-pages/component-floating-filter/examples/custom-floating-filter/_gen/packages/angular/app/number-floating-filter-component.component.ts
import { Component } from '@angular/core';
import { IFloatingFilterAngularComp } from 'ag-grid-angular';
import { IFloatingFilterParams, ISimpleFilter } from 'ag-grid-community';

export interface CustomParams {
  suppressFilterButton: boolean;
  color: string;
}
@Component({
  selector: 'number-component',
  template: `&gt;
    <input
      [style.color]="params.color"
      style="width: 30px"
      type="number"
      min="0"
      [(ngModel)]="currentValue"
      (input)="onInputBoxChanged($event)"
    />`,
})
export class NumberFloatingFilterComponent
  implements IFloatingFilterAngularComp {
  params!: IFloatingFilterParams<ISimpleFilter> & CustomParams;
  currentValue: number | null | string = null;
  style: any;

  agInit(params: IFloatingFilterParams<ISimpleFilter> & CustomParams): void {
    this.params = params;

    this.style = {
      color: params.color,
    };
  }

  onParentModelChanged(parentModel: any) {
    // When the filter is empty we will receive a null value here
    if (!parentModel) {
      this.currentValue = null;
    } else {
      this.currentValue = parentModel.filter;
    }
  }

  onInputBoxChanged() {
    if (!this.currentValue) {
      // Remove the filter
      this.params.parentFilterInstance((instance) => {
        instance.onFloatingFilterChanged(null, null);
      });
      return;
    }

    this.currentValue = Number(this.currentValue);
    this.params.parentFilterInstance((instance: any) => {
      instance.onFloatingFilterChanged('greaterThan', this.currentValue);
    });
  }
}
