// doc-pages/component-floating-filter/examples/floating-filter-component/_gen/packages/angular/app/slider-floating-filter.component.ts
import { Component } from "@angular/core";
import { AgFrameworkComponent } from "ag-grid-angular";
import {
  IFloatingFilter,
  IFloatingFilterParams,
  NumberFilterModel,
} from "ag-grid-community";

export interface SliderFloatingFilterParams extends IFloatingFilterParams {
  value: number;
  maxValue: number;
}

@Component({
  template: ` <input
    type="range"
    min="0"
    [max]="maxValue"
    data-show-value="true"
    data-popup-enabled="true"
    [(ngModel)]="currentValue"
    (ngModelChange)="valueChanged()"
  />`,
})
export class SliderFloatingFilter
  implements IFloatingFilter, AgFrameworkComponent<SliderFloatingFilterParams>
{
  private params!: SliderFloatingFilterParams;

  public maxValue!: number;
  public currentValue!: number;

  agInit(params: SliderFloatingFilterParams): void {
    this.params = params;
    this.maxValue = this.params.maxValue;
    this.currentValue = 0;
  }

  valueChanged() {
    const valueToUse = this.currentValue === 0 ? null : this.currentValue;
    this.params.parentFilterInstance(function (instance) {
      instance.onFloatingFilterChanged("greaterThan", valueToUse);
    });
  }

  onParentModelChanged(parentModel: NumberFilterModel): void {
    if (!parentModel) {
      this.currentValue = 0;
    } else {
      // note that the filter could be anything here, but our purposes we're assuming a greater than filter only,
      // so just read off the value and use that
      this.currentValue = parentModel.filter!;
    }
  }
}

// doc-pages/component-floating-filter/examples/floating-filter-component/_gen/modules/reactFunctionalTs/sliderFloatingFilter.tsx
import React, {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useState,
} from 'react';
import {
  IFloatingFilterParams,
  NumberFilterModel,
} from '@ag-grid-community/core';

export interface SliderFloatingFilterParams extends IFloatingFilterParams {
  value: number;
  maxValue: number;
}

export default forwardRef((props: SliderFloatingFilterParams, ref) => {
  const [currentValue, setCurrentValue] = useState<number>(0);

  useEffect(() => {
    let valueToUse = currentValue === 0 ? null : currentValue;
    props.parentFilterInstance((instance) =>
      instance.onFloatingFilterChanged('greaterThan', valueToUse)
    );
  }, [currentValue]);

  useImperativeHandle(ref, () => {
    return {
      onParentModelChanged(parentModel: NumberFilterModel) {
        // note that the filter could be anything here, but our purposes we're assuming a greater than filter only,
        // so just read off the value and use that
        setCurrentValue(!parentModel ? 0 : parentModel.filter!);
      },
    };
  });

  const valueChanged = (event: any) => {
    setCurrentValue(event.target.value);
  };

  const style = {
    border: '2px solid #22ff22',
    borderRadius: '5px',
    backgroundColor: '#bbffbb',
    width: '200px',
    height: '50px',
  };

  return (
    <input
      type="range"
      value={currentValue}
      min={0}
      max={props.maxValue}
      step={1}
      onChange={valueChanged}
    />
  );
});
