// doc-pages/drag-and-drop/examples/custom-drag-comp/_gen/packages/react/dragSourceRenderer.jsx
import React, { Component } from 'react';

export default class DragSourceRenderer extends Component {
  constructor(props) {
    super(props);
  }

  onDragStart = (dragEvent) => {
    var userAgent = window.navigator.userAgent;
    dragEvent.dataTransfer.setData(
      'text/plain',
      'Dragged item with ID: ' + this.props.node.data.id
    );
  };

  render() {
    return (
      <div draggable="true" onDragStart={this.onDragStart}>
        Drag Me!
      </div>
    );
  }
}

// doc-pages/drag-and-drop/examples/custom-drag-comp/_gen/modules/angular/app/drag-source-renderer.component.ts
import { ICellRendererAngularComp } from '@ag-grid-community/angular';
import { ICellRendererParams } from '@ag-grid-community/core';
import { Component } from '@angular/core';

@Component({
    selector: 'child-cell',
    template: `
        <div draggable="true" (dragstart)="onDragStart($event)">Drag Me!</div>`
})
export class DragSourceRenderer implements ICellRendererAngularComp {
    public params!: ICellRendererParams;

    agInit(params: ICellRendererParams): void {
        this.params = params;
    }

    onDragStart(dragEvent: DragEvent) {
        var userAgent = window.navigator.userAgent;
        dragEvent.dataTransfer!.setData('text/plain', 'Dragged item with ID: ' + this.params.node.data.id);
    }

    refresh(params: ICellRendererParams): boolean {
        return false;
    }
}
