// doc-pages/cell-editors/examples/dynamic-parameters/_gen/packages/react/genderCellRenderer.jsx
import React, { Component } from 'react';

export default class GenderCellRenderer extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    const image = this.props.value === 'Male' ? 'male.png' : 'female.png';
    const imageSource = `https://www.ag-grid.com/example-assets/genders/${image}`;
    return (
      <span>
        <img src={imageSource} />
        {this.props.value}
      </span>
    );
  }
}

// doc-pages/cell-editors/examples/dynamic-parameters/_gen/modules/angular/app/gender-cell-renderer.component.ts
import { ICellRendererAngularComp } from "@ag-grid-community/angular";
import { ICellRendererParams } from "@ag-grid-community/core";
import { Component } from "@angular/core";

@Component({
  selector: "app-gender-renderer",
  template: ` <span> <img [src]="imageSource" />{{ value }} </span> `,
})
export class GenderCellRenderer implements ICellRendererAngularComp {
  public imageSource!: string;
  public value: any;

  agInit(params: ICellRendererParams): void {
    const image = params.value === "Male" ? "male.png" : "female.png";
    this.imageSource = `https://www.ag-grid.com/example-assets/genders/${image}`;
    this.value = params.value;
  }
  refresh(params: ICellRendererParams): boolean {
    return false;
  }
}
