// doc-pages/component-tool-panel/examples/custom-stats/_gen/packages/angular/app/custom-stats-tool-panel.component.ts
import { Component } from '@angular/core';
import { IToolPanelAngularComp } from 'ag-grid-angular';
import { IToolPanelParams, RowNode } from 'ag-grid-community';

@Component({
  selector: 'custom-stats',
  template: ` <div style="text-align: center">
    <span>
      <h2><i class="fa fa-calculator"></i> Custom Stats</h2>
      <dl style="font-size: large; padding: 30px 40px 10px 30px">
        <dt class="totalStyle">
          Total Medals: <b>{{ numMedals }}</b>
        </dt>
        <dt class="totalStyle">
          Total Gold: <b>{{ numGold }}</b>
        </dt>
        <dt class="totalStyle">
          Total Silver: <b>{{ numSilver }}</b>
        </dt>
        <dt class="totalStyle">
          Total Bronze: <b>{{ numBronze }}</b>
        </dt>
      </dl>
    </span>
  </div>`,
  styles: [
    `
      .totalStyle {
        padding-bottom: 15px;
      }
    `,
  ],
})
export class CustomStatsToolPanel implements IToolPanelAngularComp {
  private params!: IToolPanelParams;

  public numMedals!: number;
  public numGold!: number;
  public numSilver!: number;
  public numBronze!: number;

  agInit(params: IToolPanelParams): void {
    this.params = params;

    this.numMedals = 0;
    this.numGold = 0;
    this.numSilver = 0;
    this.numBronze = 0;

    // calculate stats when new rows loaded, i.e. onModelUpdated
    this.params.api.addEventListener(
      'modelUpdated',
      this.updateTotals.bind(this)
    );
  }

  updateTotals(): void {
    let numGold = 0,
      numSilver = 0,
      numBronze = 0;

    this.params.api.forEachNode((rowNode: RowNode) => {
      const data = rowNode.data;
      if (data.gold) numGold += data.gold;
      if (data.silver) numSilver += data.silver;
      if (data.bronze) numBronze += data.bronze;
    });

    this.numMedals = numGold + numSilver + numBronze;
    this.numGold = numGold;
    this.numSilver = numSilver;
    this.numBronze = numBronze;
  }

  refresh(): void {}
}

// doc-pages/component-tool-panel/examples/custom-stats/_gen/modules/react/customStatsToolPanel.jsx
import React, { Component } from 'react';

export default class CustomStatsToolPanel extends Component {
  constructor(props) {
    super(props);

    this.state = { numMedals: 0, numGold: 0, numSilver: 0, numBronze: 0 };

    // calculate stats when new rows loaded, i.e. onModelUpdated
    this.props.api.addEventListener(
      'modelUpdated',
      this.updateTotals.bind(this)
    );
  }

  render() {
    const totalStyle = { paddingBottom: '15px' };

    return (
      <div style={{ textAlign: 'center' }}>
        <span>
          <h2>
            <i className="fa fa-calculator"></i> Custom Stats
          </h2>
          <dl style={{ fontSize: 'large', padding: '30px 40px 10px 30px' }}>
            <dt style={totalStyle}>
              Total Medals: <b>{this.state.numMedals}</b>
            </dt>
            <dt style={totalStyle}>
              Total Gold: <b>{this.state.numGold}</b>
            </dt>
            <dt style={totalStyle}>
              Total Silver: <b>{this.state.numSilver}</b>
            </dt>
            <dt style={totalStyle}>
              Total Bronze: <b>{this.state.numBronze}</b>
            </dt>
          </dl>
        </span>
      </div>
    );
  }

  updateTotals() {
    let numGold = 0,
      numSilver = 0,
      numBronze = 0;

    this.props.api.forEachNode((rowNode) => {
      const data = rowNode.data;

      if (data.gold) numGold += data.gold;
      if (data.silver) numSilver += data.silver;
      if (data.bronze) numBronze += data.bronze;
    });

    const numMedals = numGold + numSilver + numBronze;
    this.setState({ numMedals, numGold, numSilver, numBronze });
  }
}
