// doc-pages/filter-multi/examples/custom-filter/_gen/packages/reactFunctionalTs/YearFilter.tsx
import { IDoesFilterPassParams, IFilterParams } from 'ag-grid-community';
import { IFilterReactComp } from 'ag-grid-react';
import React, {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useState,
} from 'react';

export default forwardRef(({ filterChangedCallback }: IFilterParams, ref) => {
  const [isActive, setIsActive] = useState(false);
  const [activated, setActivated] = useState(false);
  const toggleFilter = (isActive: boolean) => {
    setIsActive(isActive);
    setActivated(activated || isActive);
  };

  useEffect(() => {
    if (activated) {
      filterChangedCallback();
    }
  }, [isActive, activated]);

  const setModel = (model: any) => toggleFilter(!!model);
  const isFilterActive = () => isActive;

  useImperativeHandle(ref, () => ({
    doesFilterPass: (params: IDoesFilterPassParams) => {
      return params.data.year > 2004;
    },

    isFilterActive,

    getModel: () => {
      return isFilterActive() || null;
    },

    setModel,

    onFloatingFilterChanged: (value: any) => {
      setModel(value);
    },
  }));

  return (
    <div className="year-filter">
      <label>
        <input
          type="radio"
          checked={!isActive}
          onChange={() => toggleFilter(false)}
        />{' '}
        All
      </label>
      <label>
        <input
          type="radio"
          checked={isActive}
          onChange={() => toggleFilter(true)}
        />{' '}
        After 2004
      </label>
    </div>
  );
});

// doc-pages/filter-multi/examples/custom-filter/_gen/modules/angular/app/year-filter.component.ts
import { Component } from "@angular/core";
import { IFilterAngularComp } from "@ag-grid-community/angular";
import { IDoesFilterPassParams, IFilterParams } from "@ag-grid-community/core";

@Component({
  selector: "year-filter",
  template: ` <div class="year-filter">
    <label>
      <input
        type="radio"
        name="isFilterActive"
        [checked]="!isActive"
        (change)="toggleFilter(false)"
      />
      All
    </label>
    <label>
      <input
        type="radio"
        name="isFilterActive"
        [checked]="isActive"
        (change)="toggleFilter(true)"
      />
      After 2004
    </label>
  </div>`,
})
export class YearFilter implements IFilterAngularComp {
  params!: IFilterParams;
  isActive!: boolean;

  // called on init
  agInit(params: IFilterParams): void {
    this.params = params;
    this.isActive = false;
  }

  toggleFilter(isFilterActive: boolean): void {
    this.isActive = isFilterActive;
    this.params.filterChangedCallback();
  }

  doesFilterPass(params: IDoesFilterPassParams): boolean {
    return params.data.year > 2004;
  }

  isFilterActive(): boolean {
    return this.isActive;
  }

  getModel(): boolean | null {
    return this.isFilterActive() || null;
  }

  setModel(model: any): void {
    this.toggleFilter(!!model);
  }

  onFloatingFilterChanged(value: any): void {
    this.setModel(value);
  }
}
