// doc-pages/filter-multi/examples/custom-filter/YearFloatingFilter_react.jsx
import React, { Component } from "react";

export default class YearFloatingFilter extends Component {
  constructor(props) {
    super(props);

    this.state = {
      isActive: false,
    };
  }

  toggleFilter = (isActive) => {
    this.setState({ isActive });
    this.props.parentFilterInstance((instance) =>
      instance.onFloatingFilterChanged(isActive)
    );
  };

  onParentModelChanged = (model) => {
    this.setState({ isActive: !!model });
  };

  render() {
    return (
      <div class="year-filter">
        <label>
          <input
            type="radio"
            checked={!this.state.isActive}
            onChange={() => this.toggleFilter(false)}
          />{" "}
          All
        </label>
        <label>
          <input
            type="radio"
            checked={this.state.isActive}
            onChange={() => this.toggleFilter(true)}
          />{" "}
          After 2004
        </label>
      </div>
    );
  }
}

// doc-pages/filter-multi/examples/custom-filter/_gen/modules/angular/app/year-floating-filter.component.ts
import { Component } from '@angular/core';
import { IFloatingFilterAngularComp } from '@ag-grid-community/angular';
import { IFloatingFilterParams } from '@ag-grid-community/core';
import { YearFilter } from './year-filter.component';
@Component({
    selector: 'year-floating-filter',
    template: `
        <div class="year-filter">
            <label>
                <input type="radio" name="isFloatingFilterActive" [checked]="!isActive" (change)="toggleFilter(false)" /> All
            </label>
            <label>
                <input type="radio" name="isFloatingFilterActive" [checked]="isActive" (change)="toggleFilter(true)" /> After 2004
            </label>
        </div>`
})
export class YearFloatingFilter implements IFloatingFilterAngularComp<YearFilter> {
    params!: IFloatingFilterParams<YearFilter>;
    isActive!: boolean;

    // called on init
    agInit(params: IFloatingFilterParams<YearFilter>): void {
        this.params = params;
        this.isActive = false;
    }

    toggleFilter(isFilterActive: boolean): void {
        this.isActive = isFilterActive;
        this.params.parentFilterInstance(instance => instance.onFloatingFilterChanged(isFilterActive));
    }

    onParentModelChanged(model: any): void {
        this.isActive = !!model;
    }

}
