// doc-pages/component-filter/examples/filter-component/_gen/modules/angular/app/partial-match-filter.component.ts
import { Component, ViewChild, ViewContainerRef } from "@angular/core";
import {
  IAfterGuiAttachedParams,
  IDoesFilterPassParams,
  IFilterParams,
} from "@ag-grid-community/core";
import { IFilterAngularComp } from "@ag-grid-community/angular";

@Component({
  selector: "filter-cell",
  template: `
    <div class="container">
      Partial Match Filter:
      <input
        #input
        (ngModelChange)="onChange($event)"
        [ngModel]="text"
        class="form-control"
      />
    </div>
  `,
  styles: [
    `
      .container {
        border: 2px solid #22ff22;
        border-radius: 5px;
        background-color: #bbffbb;
        width: 200px;
        height: 50px;
      }

      input {
        height: 20px;
      }
    `,
  ],
})
export class PartialMatchFilter implements IFilterAngularComp {
  private params!: IFilterParams;
  public text = "";

  @ViewChild("input", { read: ViewContainerRef })
  public input!: ViewContainerRef;

  agInit(params: IFilterParams): void {
    this.params = params;
  }

  isFilterActive(): boolean {
    return this.text != null && this.text !== "";
  }

  doesFilterPass(params: IDoesFilterPassParams): boolean {
    const { api, colDef, column, columnApi, context, valueGetter } =
      this.params;
    const { node } = params;
    const value = valueGetter({
      api,
      colDef,
      column,
      columnApi,
      context,
      data: node.data,
      getValue: (field) => node.data[field],
      node,
    })
      .toString()
      .toLowerCase();

    return this.text
      .toLowerCase()
      .split(" ")
      .every((filterWord) => value.indexOf(filterWord) >= 0);
  }

  getModel(): any {
    if (!this.isFilterActive()) {
      return null;
    }

    return { value: this.text };
  }

  setModel(model: any): void {
    this.text = model ? model.value : "";
  }

  afterGuiAttached(params: IAfterGuiAttachedParams): void {
    window.setTimeout(() => this.input.element.nativeElement.focus());
  }

  componentMethod(message: string): void {
    alert(`Alert from PartialMatchFilterComponent: ${message}`);
  }

  onChange(newValue: any): void {
    if (this.text !== newValue) {
      this.text = newValue;
      this.params.filterChangedCallback();
    }
  }
}

// doc-pages/component-filter/examples/filter-component/_gen/packages/reactFunctionalTs/partialMatchFilter.tsx
import {
  IAfterGuiAttachedParams,
  IDoesFilterPassParams,
  IFilterParams,
} from 'ag-grid-community';
import React, {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
} from 'react';
import ReactDOM from 'react-dom';

export default forwardRef((props: IFilterParams, ref) => {
  const [text, setText] = useState('');
  const refInput = useRef(null);

  useEffect(() => {
    props.filterChangedCallback();
  }, [text]);

  useImperativeHandle(ref, () => {
    return {
      isFilterActive() {
        return text != null && text !== '';
      },

      doesFilterPass(params: IDoesFilterPassParams) {
        const { api, colDef, column, columnApi, context, valueGetter } = props;
        const { node } = params;
        const value = valueGetter({
          api,
          colDef,
          column,
          columnApi,
          context,
          data: node.data,
          getValue: (field) => node.data[field],
          node,
        })
          .toString()
          .toLowerCase();

        return text
          .toLowerCase()
          .split(' ')
          .every((filterWord) => value.indexOf(filterWord) >= 0);
      },

      getModel() {
        if (!this.isFilterActive()) {
          return null;
        }

        return { value: text };
      },

      setModel(model: any) {
        setText(model ? model.value : '');
      },

      afterGuiAttached(params: IAfterGuiAttachedParams) {
        focus();
      },

      componentMethod(message: string) {
        alert(`Alert from PartialMatchFilterComponent: ${message}`);
      },
    };
  });

  const focus = () => {
    window.setTimeout(() => {
      const container = ReactDOM.findDOMNode(refInput.current) as any;
      if (container) {
        container.focus();
      }
    });
  };

  const onChange = (event: any) => {
    const newValue = event.target.value;
    if (text !== newValue) {
      setText(newValue);
    }
  };

  const style = {
    border: '2px solid #22ff22',
    borderRadius: '5px',
    backgroundColor: '#bbffbb',
    width: '200px',
    height: '50px',
  };

  return (
    <div style={style}>
      Filter:
      <input
        style={{ height: '20px' }}
        ref={refInput}
        value={text}
        onChange={onChange}
        className="form-control"
      />
    </div>
  );
});
