// doc-pages/excel-export-images/examples/excel-export-cells-with-images/_gen/modules/angular/app/country-cell-renderer.component.ts
import { Component } from "@angular/core";
import { ICellRendererParams } from "@ag-grid-community/core";
import { ICellRendererAngularComp } from "@ag-grid-community/angular";

@Component({
  selector: "simple-component",
  template: `<img
    alt="{{ params.data.country }}"
    src="{{
      params.context.base64flags[
        params.context.countryCodes[params.data.country]
      ]
    }}"
  />`,
})
export class CountryCellRenderer implements ICellRendererAngularComp {
  private params!: ICellRendererParams;

  agInit(params: ICellRendererParams): void {
    this.params = params;
  }

  refresh() {
    return false;
  }
}

// doc-pages/excel-export-images/examples/excel-export-cells-with-images/_gen/packages/reactFunctionalTs/countryCellRenderer.tsx
import React from 'react';
import { ICellRendererParams } from 'ag-grid-community';
export default (props: ICellRendererParams) => (
  <React.Fragment>
    <img
      alt={props.data.country}
      src={
        props.context.base64flags[
          props.context.countryCodes[props.data.country]
        ]
      }
    />
  </React.Fragment>
);
