// doc-pages/component-cell-editor/examples/component-editor/_gen/modules/angular/app/doubling-editor.component.ts
import { ICellEditorAngularComp } from '@ag-grid-community/angular';
import { ICellEditorParams } from '@ag-grid-community/core';
import {
  AfterViewInit,
  Component,
  ViewChild,
  ViewContainerRef,
} from '@angular/core';

@Component({
  selector: 'editor-cell',
  template: `<input
    type="number"
    [(ngModel)]="value"
    #input
    style="width: 100%"
  />`,
})
export class DoublingEditor implements ICellEditorAngularComp, AfterViewInit {
  private params!: ICellEditorParams;
  public value!: number;

  @ViewChild('input', { read: ViewContainerRef })
  public input!: ViewContainerRef;

  ngAfterViewInit() {
    // focus on the input
    setTimeout(() => this.input.element.nativeElement.focus());
  }

  agInit(params: ICellEditorParams): void {
    this.params = params;

    this.value = parseInt(this.params.value);
  }

  /* Component Editor Lifecycle methods */
  // the final value to send to the grid, on completion of editing
  getValue() {
    // this simple editor doubles any value entered into the input
    return this.value * 2;
  }

  // Gets called once before editing starts, to give editor a chance to
  // cancel the editing before it even starts.
  isCancelBeforeStart() {
    return false;
  }

  // Gets called once when editing is finished (eg if Enter is pressed).
  // If you return true, then the result of the edit will be ignored.
  isCancelAfterEnd() {
    // our editor will reject any value greater than 1000
    return this.value > 1000;
  }
}

// doc-pages/component-cell-editor/examples/component-editor/_gen/packages/react/doublingEditor.jsx
import React, { Component, createRef } from 'react';

export default class DoublingEditor extends Component {
    constructor(props) {
        super(props);

        this.inputRef = createRef();

        this.state = {
            value: parseInt(props.value)
        };
    }

    componentDidMount() {
        this.inputRef.current.focus();
    }

    /* Component Editor Lifecycle methods */

    // the final value to send to the grid, on completion of editing
    getValue() {
        // this simple editor doubles any value entered into the input
        return this.state.value * 2;
    }

    // Gets called once before editing starts, to give editor a chance to
    // cancel the editing before it even starts.
    isCancelBeforeStart() {
        return false;
    }

    // Gets called once when editing is finished (eg if Enter is pressed).
    // If you return true, then the result of the edit will be ignored.
    isCancelAfterEnd() {
        // our editor will reject any value greater than 1000
        return this.state.value > 1000;
    }

    render() {
        return (
            <input ref={this.inputRef}
                   value={this.state.value}
                   onChange={event => this.setState({value: event.target.value})}
                   style={{width: "100%"}}
            />
        );
    }
}
