// doc-pages/grouping-group-rows/examples/full-width-groups-rendering/_gen/modules/angular/app/group-row-inner-renderer.component.ts
import { ICellRendererAngularComp } from '@ag-grid-community/angular';
import { GroupCellRendererParams, RowNode } from '@ag-grid-community/core';
import { Component } from '@angular/core';

interface GroupRowParams extends GroupCellRendererParams {
  flagCodes: Record<string, string>;
}

@Component({
  selector: 'group-row-cell',
  template: ` <div class="row">
    <img
      *ngIf="flagCode"
      class="flag"
      border="0"
      width="20"
      height="15"
      [src]="flagCodeImg"
    />
    <span class="groupTitle">{{ node.key }}</span>
    <span
      class="medal gold"
      attr.aria-label="{{ node.key }} - {{ node.aggData.gold }} gold medals"
      ><i class="fas fa-medal"></i>{{ node.aggData.gold }}</span
    >
    <span
      class="medal silver"
      attr.aria-label="{{ node.key }} - {{ node.aggData.silver }} silver medals"
      ><i class="fas fa-medal"></i>{{ node.aggData.silver }}</span
    >
    <span
      class="medal bronze"
      attr.aria-label="{{ node.key }} - {{ node.aggData.bronze }} bronze medals"
      ><i class="fas fa-medal"></i>{{ node.aggData.bronze }}</span
    >
  </div>`,
  styles: [
    `
      .row {
        display: inline-block;
      }

      .groupTitle {
        font-size: 16px;
        font-weight: bold;
      }

      .medal {
        margin: 0 5px;
      }

      .gold {
        color: #e4ab11;
      }

      .silver {
        color: #bbb4bb;
      }

      .bronze {
        color: #be9088;
      }

      .flag {
        margin: 0 4px;
        position: relative;
        top: 2px;
      }
    `,
  ],
})
export class GroupRowInnerRenderer implements ICellRendererAngularComp {
  public flagCodeImg!: string;
  public flagCode!: any;
  public node!: RowNode;

  agInit(params: GroupRowParams): void {
    this.node = params.node;
    this.flagCode = params.flagCodes[params.node.key || ''];
    this.flagCodeImg = `https://flags.fmcdn.net/data/flags/mini/${this.flagCode}.png`;
  }

  refresh(): boolean {
    return false;
  }
}

// doc-pages/grouping-group-rows/examples/full-width-groups-rendering/_gen/modules/react/groupRowInnerRenderer.jsx
import React, { Component } from 'react';

export default class GroupRowInnerRenderer extends Component {
  constructor(props) {
    super(props);

    this.props = props;

    const node = this.props.node;
    const aggData = node.aggData;
    let flagCode = this.props.flagCodes[node.key];

    this.state = {
      flagCode,
      flagCodeImg: `https://flags.fmcdn.net/data/flags/mini/${flagCode}.png`,
      countryName: node.key,
      goldCount: aggData.gold,
      silverCount: aggData.silver,
      bronzeCount: aggData.bronze,
    };

    this.dataChangedListener = () => {
      this.refreshUi();
    };

    props.api.addEventListener('cellValueChanged', this.dataChangedListener);
    props.api.addEventListener('filterChanged', this.dataChangedListener);
  }

  refreshUi() {
    const node = this.props.node;
    const aggData = node.aggData;
    let flagCode = this.props.flagCodes[node.key];
    this.setState({
      flagCode,
      flagCodeImg: `https://flags.fmcdn.net/data/flags/mini/${flagCode}.png`,
      countryName: node.key,
      goldCount: aggData.gold,
      silverCount: aggData.silver,
      bronzeCount: aggData.bronze,
    });
  }

  render() {
    let img = '';
    const {
      countryName,
      goldCount,
      silverCount,
      bronzeCount,
      flagCode,
      flagCodeImg,
    } = this.state;

    if (flagCode) {
      img = (
        <img
          className="flag"
          border="0"
          width="20"
          height="15"
          src={flagCodeImg}
        />
      );
    }

    return (
      <div style={{ display: 'inline-block' }}>
        {img}
        <span className="groupTitle">{countryName}</span>
        <span
          className="medal gold"
          aria-label={`${countryName} - ${goldCount} gold medals`}
        >
          <i class="fas fa-medal"></i>
          {goldCount}
        </span>
        <span
          className="medal silver"
          aria-label={`${countryName} - ${silverCount} silver medals`}
        >
          <i class="fas fa-medal"></i>
          {silverCount}
        </span>
        <span
          className="medal bronze"
          aria-label={`${countryName} - ${bronzeCount} bronze medals`}
        >
          <i class="fas fa-medal"></i>
          {bronzeCount}
        </span>
      </div>
    );
  }

  componentWillUnmount() {
    this.props.api.removeEventListener(
      'cellValueChanged',
      this.dataChangedListener
    );
    this.props.api.removeEventListener(
      'filterChanged',
      this.dataChangedListener
    );
  }
}
