// doc-pages/master-detail-custom-detail/examples/custom-detail-with-refresh/_gen/packages/angular/app/detail-cell-renderer.component.ts
import { Component } from "@angular/core";
import { ICellRendererAngularComp } from "ag-grid-angular";
import { ICellRendererParams } from "ag-grid-community";

@Component({
  selector: "app-detail-cell-renderer",
  template: `
    <div>
      <form>
        <div>
          <p>
            <label>
              Calls:<br />
              <input type="text" value="{{ callsCount }}" />
            </label>
          </p>
          <p>
            <label>
              Last Updated:
              {{ now }}
            </label>
          </p>
        </div>
      </form>
    </div>
  `,
})
export class DetailCellRenderer implements ICellRendererAngularComp {
  public callsCount!: number;
  public now!: string;

  // called on init
  agInit(params: ICellRendererParams): void {
    this.callsCount = params.data.calls;
    this.now = new Date().toLocaleTimeString();
  }

  // called when the cell is refreshed
  refresh(params: ICellRendererParams): boolean {
    // check and see if we need to get the grid to tear this
    // component down and update it again
    if (params.data.calls != this.callsCount) {
      return false;
    } else {
      return true;
    }
  }
}

// doc-pages/master-detail-custom-detail/examples/custom-detail-with-refresh/_gen/packages/react/detailCellRenderer.jsx
import React, { Component } from 'react';

export default class DetailCellRenderer extends Component {
  constructor(props) {
    super(props);

    this.state = {
      callCount: props.data.calls,
      lastUpdated: new Date().toLocaleTimeString(),
    };
  }

  refresh(params) {
    // check and see if we need to get the grid to tear this
    // component down and update it again
    return params.data.calls === this.state.callCount;
  }

  render() {
    return (
      <div>
        <form>
          <div>
            <p>
              <label>
                Calls:
                <br />
                <input
                  type="text"
                  value={this.state.callCount}
                  onChange={(e) => this.setState({ callCount: e.target.value })}
                />
              </label>
            </p>
            <p>
              <label>Last Updated: {this.state.lastUpdated}</label>
            </p>
          </div>
        </form>
      </div>
    );
  }
}
