// doc-pages/component-floating-filter/examples/custom-floating-filter/_gen/modules/angular/app/number-floating-filter-component.component.ts
import { Component } from "@angular/core";
import { IFloatingFilterAngularComp } from "@ag-grid-community/angular";
import { IFloatingFilterParams, ISimpleFilter } from "@ag-grid-community/core";

export interface CustomParams {
  suppressFilterButton: boolean;
  color: string;
}
@Component({
  selector: "number-component",
  template: `&gt;
    <input
      [style.color]="params.color"
      style="width: 30px"
      type="number"
      min="0"
      [(ngModel)]="currentValue"
      (input)="onInputBoxChanged($event)"
    />`,
})
export class NumberFloatingFilterComponent
  implements IFloatingFilterAngularComp
{
  params!: IFloatingFilterParams<ISimpleFilter> & CustomParams;
  currentValue: number | null | string = null;
  style: any;

  agInit(params: IFloatingFilterParams<ISimpleFilter> & CustomParams): void {
    this.params = params;

    this.style = {
      color: params.color,
    };
  }

  onParentModelChanged(parentModel: any) {
    // When the filter is empty we will receive a null value here
    if (!parentModel) {
      this.currentValue = null;
    } else {
      this.currentValue = parentModel.filter;
    }
  }

  onInputBoxChanged() {
    if (!this.currentValue) {
      // Remove the filter
      this.params.parentFilterInstance((instance) => {
        instance.onFloatingFilterChanged(null, null);
      });
      return;
    }

    this.currentValue = Number(this.currentValue);
    this.params.parentFilterInstance((instance: any) => {
      instance.onFloatingFilterChanged("greaterThan", this.currentValue);
    });
  }
}

// doc-pages/component-floating-filter/examples/custom-floating-filter/_gen/modules/react/numberFloatingFilterComponent.jsx
import React, { Component, createRef, Fragment } from "react";

export default class NumberFloatingFilterComponent extends Component {
  constructor(props) {
    super(props);

    this.state = {
      currentValue: null,
    };

    this.inputRef = createRef();
  }

  onParentModelChanged(parentModel) {
    // When the filter is empty we will receive a null value here
    if (!parentModel) {
      this.inputRef.current.value = "";
      this.setState({ currentValue: null });
    } else {
      this.inputRef.current.value = parentModel.filter + "";
      this.setState({ currentValue: parentModel.filter });
    }
  }

  onInputBoxChanged = (input) => {
    if (input.target.value === "") {
      // Remove the filter
      this.props.parentFilterInstance((instance) => {
        instance.onFloatingFilterChanged(null, null);
      });
      return;
    }

    this.setState({ currentValue: Number(input.target.value) });
    this.props.parentFilterInstance((instance) => {
      instance.onFloatingFilterChanged("greaterThan", input.target.value);
    });
  };

  render() {
    const style = {
      color: this.props.color,
      width: "30px",
    };

    return (
      <Fragment>
        &gt;{" "}
        <input
          ref={this.inputRef}
          style={style}
          type="number"
          min="0"
          onInput={this.onInputBoxChanged}
        />
      </Fragment>
    );
  }
}
