// doc-pages/grouping-footers/examples/customising-footer-cells/_gen/modules/angular/app/my-inner-renderer.component.ts
import { Component } from '@angular/core';
import { ICellRendererAngularComp } from '@ag-grid-community/angular';
import { ICellRendererParams } from '@ag-grid-community/core';


@Component({
    selector: 'total-value-component',
    template: `<span style="color: {{color}}; font-weight: {{fontWeight}};">{{prefix}} {{cellValue}}</span>`
})
export class MyInnerRenderer implements ICellRendererAngularComp {

    public cellValue = '';
    public color = '';
    public fontWeight = '';
    public prefix = '';

    // gets called once before the renderer is used
    agInit(params: ICellRendererParams): void {
        this.cellValue = params.value;
        this.color = params.node.footer ? 'navy' : '';
        this.fontWeight = (params.node.footer && params.node.level === -1) ? 'bold' : '';
        if (params.node.footer) {
            this.prefix = (params.node.level === -1) ? 'Grand Total' : 'Sub Total';
        }
    }

    refresh(params: ICellRendererParams) {
        return false;
    }
}

// doc-pages/grouping-footers/examples/customising-footer-cells/_gen/packages/react/myInnerRenderer.jsx
import React, { Component } from "react";

export default class MyInnerRenderer extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    const footer = this.props.node.footer;
    const isRootLevel = this.props.node.level === -1;
    const value = this.props.value;

    if (footer) {
      if (isRootLevel) {
        return (
          <span style={{ color: "navy", fontWeight: "bold" }}>Grand Total</span>
        );
      } else {
        return <span style={{ color: "navy" }}>Sub Total ${value}</span>;
      }
    } else {
      return <span>{value}</span>;
    }
  }
}
