// doc-pages/excel-export-rows/examples/excel-export-multi-line/_gen/modules/react/multilineCellRenderer.jsx
import React, { Component } from 'react';

// simple cell renderer returns dummy buttons. in a real application, a component would probably
// be used with operations tied to the buttons. in this example, the cell renderer is just for
// display purposes.
export default class MultilineComponent extends Component {
  constructor(props) {
    super(props);

    this.value = props.value.replace('\n', '<br/>');
  }

  render() {
    return <div dangerouslySetInnerHTML={{ __html: this.value }}></div>;
  }
}

// doc-pages/excel-export-rows/examples/excel-export-multi-line/_gen/packages/angular/app/multiline-cell-renderer.component.ts
import { Component } from '@angular/core';
import { ICellRendererParams } from 'ag-grid-community';
import { ICellRendererAngularComp } from 'ag-grid-angular';

// simple cell renderer returns dummy buttons. in a real application, a component would probably
// be used with operations tied to the buttons. in this example, the cell renderer is just for
// display purposes.
@Component({
    selector: 'simple-component',
    template: `<div [innerHTML]="value"></div>`
})
export class MultilineCellRenderer implements ICellRendererAngularComp {
    private params!: ICellRendererParams;
    private value: any;

    agInit(params: ICellRendererParams): void {
        this.params = params;
        this.value = params.value.replace('\n', '<br/>')
    }

    refresh() {
        return false
    }
}
